### PR TITLE
upgrade testng version to 7.8.0

### PR DESCRIPTION
**Pull request by xiangfu0**
- Upgrade Testng to 7.8.0
- Upgrade Maven surefire version to 3.1.2
- Simplify `maven-surefire-plugin` usage in other module
- Fixing some flaky tests in `OfflineClusterIntegrationTest`

### CODE REVIEW

**Comment by xiangfu0** [comment]
finally got this upgraded after fixing this: https://github.com/apache/pinot/pull/11720

**Review by Jackie-Jiang — APPROVED** [review]

**Comment by deemoliu** [comment]
hi @xiangfu0 

I observed some command are not working after test verison bump.

For example 
```
mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip
```
and I got 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project pinot-spi: No tests matching pattern "InterSegmentAggregationMultiValueRawQueriesTest" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pinot-spi
```

do you have an equivalent testing command that has similar function with `mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip`?

**Comment by xiangfu0** [comment]
> hi @xiangfu0
> 
> I observed some command are not working after test verison bump.
> 
> For example
> 
> ```
> mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip
> ```
> 
> and I got
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project pinot-spi: No tests matching pattern "InterSegmentAggregationMultiValueRawQueriesTest" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :pinot-spi
> ```
> 
> do you have an equivalent testing command that has similar function with `mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip`?

True, I can also reproduce this, will look into it more.
For now you can enter into the folder then run it: 
```
cd pinot-core
mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip
```

**Comment by xiangfu0** [comment]
> hi @xiangfu0
> 
> I observed some command are not working after test verison bump.
> 
> For example
> 
> ```
> mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip
> ```
> 
> and I got
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project pinot-spi: No tests matching pattern "InterSegmentAggregationMultiValueRawQueriesTest" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :pinot-spi
> ```
> 
> do you have an equivalent testing command that has similar function with `mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip`?

you can use `-Dsurefire.failIfNoSpecifiedTests=false` instead of `-DfailIfNoTests=false`

**Comment by xiangfu0** [comment]
> > hi @xiangfu0
> > I observed some command are not working after test verison bump.
> > For example
> > ```
> > mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and I got
> > ```
> > [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project pinot-spi: No tests matching pattern "InterSegmentAggregationMultiValueRawQueriesTest" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]
> > [ERROR] 
> > [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> > [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> > [ERROR] 
> > [ERROR] For more information about the errors and possible solutions, please read the following articles:
> > [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> > [ERROR] 
> > [ERROR] After correcting the problems, you can resume the build with the command
> > [ERROR]   mvn <args> -rf :pinot-spi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > do you have an equivalent testing command that has similar function with `mvn test -Dtest=InterSegmentAggregationMultiValueRawQueriesTest -DfailIfNoTests=false -Dcheckstyle.skip`?
> 
> you can use `-Dsurefire.failIfNoSpecifiedTests=false` instead of `-DfailIfNoTests=false`

for simplicity, this is the most effective way:
```
mvn test  -pl :pinot-core -am  "-Dtest=*InterSegmentAggregationMultiValueRawQueriesTest"  -Dcheckstyle.skip -Dsurefire.failIfNoSpecifiedTests=false
```

**Comment by deemoliu** [comment]
i see. thanks @xiangfu0, i tried the last command and it worked perfectly.

**Pull request merged**
