### PR TITLE
Round Robin IP addresses when retry uploading/downloading segments

### PR DESCRIPTION
**Pull request by mqliang**
## Description

When minion/server upload/download segments to/from deep store, the deep store may be backed by multiple hosts, while minion/server may always try to upload/download from the same host because: 1) DNS may not RR the IP addresses 2) OS cache the DNS result.

This RB:
* Round Robin IP addresses when retry upload/downloading segments
* Make 404 a temporary exception, as the deep store may be backed by multiple hosts, if singe host is down, can retry with another host.

cc @jackjlli 
 
## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by mqliang** [comment]
test failed due to flaky issue. close&re-open to trigger a re-run

**Comment by mqliang** [comment]
Integration test of `BasicAuthTlsRealtimeIntegrationTest` will failed if round round ip address between 127.0.0.1 (IPV4) and [0:0:0:0:0:0:0:1] (IPV6) for host name "localhost". This is because `BasicAuthTlsRealtimeIntegrationTest` use file [tlstest.jks](https://github.com/apache/pinot/blob/2de40fde8051c2c0281416c2da11c179c2190435/pinot-integration-tests/src/test/resources/tlstest.jks) for TLS validation, but the [tlstest.jks](https://github.com/apache/pinot/blob/2de40fde8051c2c0281416c2da11c179c2190435/pinot-integration-tests/src/test/resources/tlstest.jks) file does not contains cert for [0:0:0:0:0:0:0:1]

I currently fix integration test by disabling the IP address RR for "localhost". A fundamental fix should be update the  [tlstest.jks](https://github.com/apache/pinot/blob/2de40fde8051c2c0281416c2da11c179c2190435/pinot-integration-tests/src/test/resources/tlstest.jks) file.

@apucher I see you add the HTTPS test in https://github.com/apache/pinot/pull/7010/, can you give me some instruction regarding generating `tlstest.jks` file for both: 
* localhost
* 127.0.0.1
* [0:0:0:0:0:0:0:1]

**Comment by apucher** [comment]
@mqliang just create a self-signed certificate with all alt subject name in a JKS file and replace the existing one. Example here: https://stackoverflow.com/questions/8744607/how-to-add-subject-alernative-name-to-ssl-certs

**Comment by mqliang** [comment]
@apucher Test passed locally. Thanks for the prompt help!

**Comment by mqliang** [comment]
***Potential issue of this RB***: if the deepstore address is a LB address, and if the LB be configed as "disallow direct access by IP address", after this RB, all segment upload/download will fail. Please change your LB config if need be.

**Comment by apucher** [comment]
@mqliang this should definitely go into the release notes above

**Comment by mqliang** [comment]
@apucher I turns out we can add some code to tolerate this situation -- by adding a "HOST" HTTP header. I have added that piece of code.

**Comment by mqliang** [comment]
integration test failed due to flaky issue. 
```
Error:  Failures: 
Error:    RealtimeKinesisIntegrationTest.setUp:135->startKinesis:224 » LocalstackDocker ...
Error:    RealtimeKinesisIntegrationTest.tearDown:453->ControllerTest.dropRealtimeTable:550->ControllerTest.sendDeleteRequest:716->ControllerTest.sendDeleteRequest:729 » FileNotFound
[INFO] 
Error:  Tests run: 102, Failures: 2, Errors: 0, Skipped: 2
```
close & re-open to trigger a re-run:

**Comment by mqliang** [comment]
Quick start on JDK 10 infinitely loop:
```
+ sleep 1
+ true
+ kill -0 6278
+ sleep 1
+ true
+ kill -0 6278
```

Which is flaky, close & re-open to trigger a re-run.

**Pull request merged**
