### PR TITLE
support refreshing realtime segments

### PR DESCRIPTION
**Pull request by kmozaid**

### CODE REVIEW

**Comment by sajjad-moradi** [comment]
@kmozaid This is being done as part of opening up upload endpoint for realtime segments - in this PR: https://github.com/apache/pinot/pull/8584

**Comment by kmozaid** [comment]
> @kmozaid This is being done as part of opening up upload endpoint for realtime segments - in this PR: #8584

ohk, then I can close this PR, right? Also I don't see the below change in `RealtimeTableDataManager` , How Server is going to handle `REFRESH_SEGMENT` message sent by controller when segment is uploaded? Did you verify that segment uploaded are queryable in your code?

```
  @Override
  public void addSegment(File indexDir, IndexLoadingConfig indexLoadingConfig)
      throws Exception {
    Schema schema = ZKMetadataProvider.getTableSchema(_propertyStore, _tableNameWithType);
    addSegment(ImmutableSegmentLoader.load(indexDir, indexLoadingConfig, schema));
  }
```

JFYI, message which controller send to server -
```
ZnRecord=87e551ff-cc98-4fdf-b861-6be3b8d561bd, {CREATE_TIMESTAMP=1650873841979, EXECUTE_START_TIMESTAMP=1650873854007, MSG_ID=87e551ff-cc98-4fdf-b861-6be3b8d561bd, MSG_STATE=new, MSG_SUBTYPE=REFRESH_SEGMENT, MSG_TYPE=USER_DEFINE_MSG, PARTITION_NAME=transcript__0__2__20220425T0634Z, RESOURCE_NAME=transcript_REALTIME, RETRY_COUNT=0, SRC_CLUSTER=PinotCluster, SRC_INSTANCE_TYPE=PARTICIPANT, SRC_NAME=Controller_localhost_9001, TGT_NAME=Server_localhost_8001, TGT_SESSION_ID=1000232d2430120, TIMEOUT=-1, segmentName=transcript__0__2__20220425T0634Z, tableName=transcript_REALTIME}{}{}, Stat=Stat {_version=0, _creationTime=1650873842026, _modifiedTime=1650873842026, _ephemeralOwner=0}
```

**Comment by kmozaid** [comment]
> > @kmozaid This is being done as part of opening up upload endpoint for realtime segments - in this PR: #8584
> 
> ohk, then I can close this PR, right? Also I don't see the below change in `RealtimeTableDataManager` , How Server is going to handle `REFRESH_SEGMENT` message sent by controller when segment is uploaded? Did you verify that segment uploaded are queryable in your code?
> 
> ```
>   @Override
>   public void addSegment(File indexDir, IndexLoadingConfig indexLoadingConfig)
>       throws Exception {
>     Schema schema = ZKMetadataProvider.getTableSchema(_propertyStore, _tableNameWithType);
>     addSegment(ImmutableSegmentLoader.load(indexDir, indexLoadingConfig, schema));
>   }
> ```
> 
> JFYI, message which controller send to server -
> 
> ```
> ZnRecord=87e551ff-cc98-4fdf-b861-6be3b8d561bd, {CREATE_TIMESTAMP=1650873841979, EXECUTE_START_TIMESTAMP=1650873854007, MSG_ID=87e551ff-cc98-4fdf-b861-6be3b8d561bd, MSG_STATE=new, MSG_SUBTYPE=REFRESH_SEGMENT, MSG_TYPE=USER_DEFINE_MSG, PARTITION_NAME=transcript__0__2__20220425T0634Z, RESOURCE_NAME=transcript_REALTIME, RETRY_COUNT=0, SRC_CLUSTER=PinotCluster, SRC_INSTANCE_TYPE=PARTICIPANT, SRC_NAME=Controller_localhost_9001, TGT_NAME=Server_localhost_8001, TGT_SESSION_ID=1000232d2430120, TIMEOUT=-1, segmentName=transcript__0__2__20220425T0634Z, tableName=transcript_REALTIME}{}{}, Stat=Stat {_version=0, _creationTime=1650873842026, _modifiedTime=1650873842026, _ephemeralOwner=0}
> ```

Refresh Message is being sent here -
https://github.com/apache/pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/api/upload/ZKOperator.java#L204

Message is being handled here -
https://github.com/apache/pinot/blob/master/pinot-server/src/main/java/org/apache/pinot/server/starter/helix/SegmentMessageHandlerFactory.java#L96

This is where Unsupported exception is thrown if you don't add implementation of addSegment() method.
https://github.com/apache/pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/data/manager/BaseTableDataManager.java#L373

**Comment by sajjad-moradi** [comment]
> > @kmozaid This is being done as part of opening up upload endpoint for realtime segments - in this PR: #8584
> 
> ohk, then I can close this PR, right? Also I don't see the below change in `RealtimeTableDataManager` , How Server is going to handle `REFRESH_SEGMENT` message sent by controller when segment is uploaded? Did you verify that segment uploaded are queryable in your code?
> 

Yes you can close this PR.
Also good catch on segment refresh message handling on server side. In the integration test that I modified to upload realtime segments, I considered the refresh use case and modified the CRC of the existing segment on ZK for it, but in servers, the CRC remains the same on the local file and the segment refresh path doesn't get to the point to actually download the segment - it uses the existing segment since the CRC of the uploaded segment and the one residing on server are the same. I'll make the changes and try to update the integration test to change the CRC of the local file on server side.

**Comment by kmozaid** [comment]
> 

Sure, I will close this PR.

On segment refresh, I think you should do following -

1. Upload a segment (say, with segmenName: test_segment_1) to a realtime table.
2. Upload a segment with the same name that you used in step 1 and but with some different data in it (similar to purge task which removes some records and upload segment with same name).
3. Assert that records are updated (may be count has changed if some records were removed in step 2) when you query the table.

**Pull request closed without merging**
