### PR TITLE
[hotfix] fix pom warnings

### PR DESCRIPTION
**Pull request by walterddr**

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
@gortiz Can you please help take a look if this is the correct way to override the jackson version.

**Comment by KKcorps** [comment]
Spark has a very strict dependency with jackson. We can use whatever we want, but we need to ensure spark dep is under provided scope and jackson is shaded in all plugins (not just spark)

**Comment by walterddr** [comment]
> Spark has a very strict dependency with jackson. We can use whatever we want, but we need to ensure spark dep is under provided scope and jackson is shaded in all plugins (not just spark)

found the issue was one of the legacy PQL query options.

**Comment by walterddr** [comment]
> @gortiz Can you please help take a look if this is the correct way to override the jackson version.

@Jackie-Jiang ^ this is not a override. it is fixing a warning 
```
[WARNING] Some problems were encountered while building the effective model for org.apache.pinot:pinot-batch-ingestion-spark-2.4:jar:0.11.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.fasterxml.jackson.core:jackson-core:jar -> version (?) vs ${spark2.jackson.version} @ line 175, column 17
```
and
```
[WARNING] Some problems were encountered while building the effective model for org.apache.pinot:pinot-tools:jar:0.11.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: xml-apis:xml-apis:jar -> duplicate declaration of version (?) @ line 262, column 17
```

> Spark has a very strict dependency with jackson. We can use whatever we want, but we need to ensure spark dep is under provided scope and jackson is shaded in all plugins (not just spark)

yeah I think this was exactly the point of this PR.

**Review by jackjlli — APPROVED** [review]

**Pull request merged**
