### PR TITLE
Bumping calcite to most recent version to pick up latest SQL dialects

### PR DESCRIPTION
**Pull request by timsants**
## Description
Bumping calcite version to get new supported SQL dialects.

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by siddharthteotia** [comment]
Ok with the version upgrade as long as functionality doesn't break. 

Just curious which new SQL dialects are we planning to use with the upgraded version ?

**Comment by mayankshriv** [comment]
Would be good to ensure that the new version does not have any backward incompatibilites that might affect us.

**Comment by mayankshriv** [comment]
> Ok with the version upgrade as long as functionality doesn't break.
> 
> Just curious which new SQL dialects are we planning to use with the upgraded version ?

+1 on both counts.

**Comment by timsants** [comment]
Closing PR as this version bump causes test failure in OSS. Will revisit other approaches.

**Pull request closed without merging**
