### PR TITLE
use static TypeReference object

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ready for review

**Comment by sullis** [comment]
please review  @gortiz @Jackie-Jiang

**Review by Jackie-Jiang — COMMENTED** [review]
Let's add a method `Map<String, Object> stringToMap(String jsonString)` into `JsonUtils`

**Comment by sullis** [comment]
> Let's add a method `Map<String, Object> stringToMap(String jsonString)` into `JsonUtils`

Done.

**Comment by Jackie-Jiang** [comment]
Sorry didn't notice these 2 references are different.. In that case the previous commit is more clear

**Comment by sullis** [comment]
> Sorry didn't notice these 2 references are different.. In that case the previous commit is more clear

Ack.  I have removed JsonUtils stringToMap. I just pushed the revert.

**Comment by sullis** [comment]
Test suite passes

**Comment by sullis** [comment]
Ready for review

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
