### PR TITLE
[cleanup] remove LLCSegmentName getTableName

### PR DESCRIPTION
**Pull request by walterddr**
table name should not be derived from SegmentName.

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
Hmm, do you want to allow pushing segments to a different table?

**Comment by walterddr** [comment]
The goal is to decouple segment name from table name usage. In all the usage of `LLCSegmentName.getTableName` they can either get the table in question from context within the function scope or they can derive that from its callers. 

I think we already clean up a lot of the deriving from segment to table naming. this seems to be the last one and keeping segment name and table name clean and separate makes it much easier to manage IMO..

This is just a draft to see how many tests are failing (apparently there's a lot)..

Do we have any thoughts on making this clean up
CC @mcvsubbu @xiangfu0 @mayankshriv @npawar

**Comment by mcvsubbu** [comment]
There was a discussion on this topic a while ago on an issue that I am not able to find now.

There are some minor changes that can be made in the PR itself, but I have no problem in cleaning this up and not making an assumption.

**Comment by mcvsubbu** [comment]
Issue https://github.com/apache/pinot/issues/7594

**Pull request closed without merging**
