### PR TITLE
Optimize single element ArrayList creation

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Replace `new ArrayList<>(Collections.singletonList(e))` with a util function

### CODE REVIEW

**Review by xiangfu0 — APPROVED** [review]

**Comment by FelixGV** [comment]
Would it not be more optimal to return just `Collections.singletonList(e)` rather than wrapping the one element in an `ArrayList`? Memory-wise, the singleton list should have less memory overhead since it doesn't carry an array. The singleton list, however, is immutable, and will throw `UnsupportedOperationException` if you try to add more items into it, which may be either good or bad, depending on the use case.

If an immutable single element list is what you're looking for, then I would think singletonList is ideal. Moreover, in cases where you're passing a constant into the list (e.g. when you're passing `"*"` or `ExpressionContext.forIdentifier("*")`) then you could allocate that statically and keep reusing the same instance, which could be even more efficient.

The above may or may not make sense in this context, so take it with a grain of salt. I am always curious about performance-related work in other projects, to see if I can leverage them elsewhere, which is why I looked at this PR (: ...

**Comment by richardstartin** [comment]
Do we have any measurements which indicate this is worthwhile? This sort of thing can be surprising.

**Comment by richardstartin** [comment]
This appears to amount to a slight regression, at least it's in the noise, on a tiny baseline cost:

```java
@State(Scope.Benchmark)
public class OneElementList {

  @Param("*")
  String value;

  @Benchmark
  public List<String> singletonList() {
    return new ArrayList<>(Collections.singletonList(value));
  }

  @Benchmark
  public List<String> optimized() {
    List<String> list = new ArrayList<>(1);
    list.add(value);
    return list;
  }
}
```

```
Benchmark                     (value)  Mode  Cnt  Score   Error  Units
OneElementList.optimized            *  avgt    5  6.138 ± 0.127  ns/op
OneElementList.singletonList        *  avgt    5  5.224 ± 0.541  ns/op
```

With the change 48 bytes is allocated per list, before it was 72 bytes. Maybe it's worthwhile for those 24 bytes.

**Comment by xiangfu0** [comment]
The issue here is that we need to perform a recursive check for expression override.
If not changing this to a mutable single array list, then we need to check if the list is immutable which may bring in more overhead.

**Comment by Jackie-Jiang** [comment]
Since the perf number is so close, probably not worth the effort of maintaining the code

**Pull request closed without merging**
