### PR TITLE
Make the SQL Editor box expandable

### PR DESCRIPTION
**Pull request by hristo-stripe**
## Description

The default size of the SQL Editor box is such that it only shows
about 5 lines of text. The SQL Editor uses [react-codemirror2](https://github.com/scniro/react-codemirror2) which recommends
using [re-resizable](https://github.com/bokuweb/re-resizable) to make the editor field resizable.

This patch adds a new NPM library dependency on `re-resizable` and adds
a react component to make the field expandable. As a way to make the change minimal,
the patch only allows the field to be vertically expandable and keeps the default
size the same (height is 100px).

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
No.

Does this PR fix a zero-downtime upgrade introduced earlier?
No.

Does this PR otherwise need attention when creating release notes? Things to consider:
No.

## Release Notes

n/a

## Documentation

n/a

### CODE REVIEW

**Comment by hristo-stripe** [comment]
@jackjlli and @Jackie-Jiang would you review this PR? Let me know if I should request a review from someone else.

**Comment by Jackie-Jiang** [comment]
I'm asking @shahsank3t to take a look

**Review by shahsank3t — APPROVED** [review]
+1 LGTM.
Thank you for taking care of this @hristo-stripe

**Comment by hristo-stripe** [comment]
Thank you, @shahsank3t!

**Comment by Jackie-Jiang** [comment]
@hristo-stripe Seems there is a conflict with a recently merged change. Can you please resolve the conflict? Then I'll merge it. Thanks for the contribution!

**Comment by hristo-stripe** [comment]
@Jackie-Jiang done. Thanks!

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
