### PR TITLE
[feature] Pass null literal as a boolean null value thrift

### PR DESCRIPTION
**Pull request by 61yao**
Pass null literal as a boolean null value in thrift. 

The field can only be set to true. This is needed since thrift doesn't support unset fields.

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
Changing only the thrift file is not enough. You'll need to re-compile it so that the change is reflected in the java classes

**Comment by 61yao** [comment]
> Changing only the thrift file is not enough. You'll need to re-compile it so that the change is reflected in the java classes

@Jackie-Jiang Added gen java code. PTAL

**Review by Jackie-Jiang — APPROVED** [review]

**Comment by Jackie-Jiang** [comment]
Please create an issue with the design, and link all the PRs to the issue for easier tracking

**Comment by 61yao** [comment]
> Please create an issue with the design, and link all the PRs to the issue for easier tracking

Added an issue. I haven't figured out all of the design so I put a TODO there.

https://github.com/apache/pinot/issues/10252

**Comment by 61yao** [comment]
@zhtaoxiang

**Pull request merged**
