### PR TITLE
[hotfix] relax tableconfig validation for realtime to offline task

### PR DESCRIPTION
**Pull request by walterddr**
There are situations when realtime-to-offline task transfers data to an upsert enabled hybrid table. so relaxing this check.

### CODE REVIEW

**Review by richardstartin — APPROVED** [review]

**Comment by walterddr** [comment]
@npawar does this relaxation make sense? I think originally the no-upsert rule applies to the offline portion of the table correct? if I understand correctly this check can be relaxed

**Comment by walterddr** [comment]
I dont think this is the right fix. we should add another configuration to alter this behavior as it will cause weird behavior on some other use cases. closing for now and going back to the drawing board.

**Review by npawar — APPROVED** [review]

**Comment by npawar** [comment]
> @npawar does this relaxation make sense? I think originally the no-upsert rule applies to the offline portion of the table correct? if I understand correctly this check can be relaxed

as per the many offline disciussions, let's remove this check. This was anyway catching only upsert + realtimeToOffline, and not the general upsert + hybrid case that we were intending to prevent.

**Comment by npawar** [comment]
Motivation from Vibhor Jain on slack
```Thanks for looking into this.
Ours is a hybrid table where realtime is holding data for say 7 days and minion is moving it to offline (to support backfill for future needs).
Now, duplicates occur in small batches for us since our Flink flows are at least once. There is no scenario where a duplicate is coming after say 4 days.
So we only need UPSERT for realtime. Blocking this for hybrid table is not working out for us.
Till now, we were handling deduplication flow for our hybrid table in 2 steps:
realtime handles it via UPSERT.
offline handles it via mergeType: "dedup" in "RealtimeToOfflineSegmentsTask" configs. This was working perfectly fine and no duplicates were seen.
Pls note, we understand UPSERT cannot work across realtime and offline tables together. We were leveraging this functionality only for REALTIME.
UPSERT documentation clearly states it's for REALTIME. So if I'm using it for the hybrid table, it should be allowed (given the limitation to real time only that's already documented).
Let me know if you need further info on this one.
```

**Comment by Jackie-Jiang** [comment]
Upsert won't work on hybrid table, and I think we should have this validation by default.
To workaround the cases where user knows it doesn't work but still want to bypass the validation, we can add some skip validation rules as an additional parameter when updating table config/schema.

**Comment by walterddr** [comment]
I am going to close this for now since it seems to be a valid checker. i will create an explicit validation skipping rule then.

**Pull request closed without merging**
