### PR TITLE
cleanup: maven no transfer progress

### PR DESCRIPTION
**Pull request by sullis**
Maven ntp ( 'no transfer progress' ) reduces the amount of Maven output in the CI build.

### CODE REVIEW

**Comment by sullis** [comment]
WDYT @xiangfu0

**Comment by sullis** [comment]
cc: @gortiz

**Comment by gortiz** [comment]
Does it actually affects anything? From [maven docs](https://maven.apache.org/docs/3.6.1/release-notes.html#user-visible-changes) it says:

> Maven has now a an option to suppress the transfer progress when downloading/uploading in interactive mode.

We actually run in batch mode (see the `-B`) so there shouldn't be an actual difference, right?

**Comment by sullis** [comment]
when I run this command:

```
mvn -B clean compile
```

the output includes the download of each individual jar file:

```
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm/9.3/asm-9.3.jar (122 kB at 399 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
```

When I run the same command with the "ntp" option

```
mvn -B -ntp clean compile
```

the output does not include any of the "download" messages

**Comment by sullis** [comment]
the Netty project uses "-B" and "-ntp" in the GitHub Actions build

image

**Review by Jackie-Jiang — APPROVED** [review]
The logs printed while building the project are reduced by about half (4000+ to 2000+). I'm good with the change, thanks!

**Pull request merged**
