### PR TITLE
Strip Matrix parameter from BasePath check

### PR DESCRIPTION
**Pull request by praveenc7**
## Summary
Modify Parser to strip matrix parameter when checking for basePath

## Testing
unit test added

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
IIUC, the intention is to avoid bypassing the `isBaseFile()` check?
What is the purpose of `isBaseFile()`? I'd suggest making it very limited (e.g. only allow `"."`, or is it even required?)

**Comment by praveenc7** [comment]
> IIUC, the intention is to avoid bypassing the `isBaseFile()` check? What is the purpose of `isBaseFile()`? I'd suggest making it very limited (e.g. only allow `"."`, or is it even required?)

 I’m not aware of the historical reasons for why this check is necessary, This type of check is generally used to filter paths, likely to allow access only to certain files, such as configuration files or top-level resources, while excluding directories and complex paths.
 
 For example :` https://example.com/file.txt` , `https://example.com/image.png`
 
 Let me make the check a more tighter

**Comment by Jackie-Jiang** [comment]
@soumitra-st Can you help take a look? Which path do we need to allow bypassing the auth check?

I want to make this whitelist very restricted so that only the allowed path can bypass the auth check. This way we can avoid other possible attacks, instead of explicitly handling them one by one.

**Comment by soumitra-st** [comment]
> Modify Parser to strip matrix parameter when checking for basePath

@praveenc7 ,Pinot does not support MatrixParam. Can you elaborate on the context of handling MatrixParam for top-level resources only?

**Comment by soumitra-st** [comment]
> @soumitra-st Can you help take a look? Which path do we need to allow bypassing the auth check?
> 
> I want to make this whitelist very restricted so that only the allowed path can bypass the auth check. This way we can avoid other possible attacks, instead of explicitly handling them one by one.

The current whitelist paths are [HERE](https://github.com/apache/pinot/blob/b06c0613fe76c4c5e9c6989e010642a39b60c1d8/pinot-controller/src/main/java/org/apache/pinot/controller/api/access/AuthenticationFilter.java#L53):
      new HashSet<>(Arrays.asList("", "help", "auth/info", "auth/verify", "health"));

In addition to the above whitelisted paths, all top files having at least one '.' are allowed. This is likely done to allow access to top-level resource files. If we need to remove implicit access to all the top-level resources, we must figure out the list and add it to the UNPROTECTED_PATHS.

**Comment by praveenc7** [comment]
> > Modify Parser to strip matrix parameter when checking for basePath
> 
> @praveenc7 ,Pinot does not support MatrixParam. Can you elaborate on the context of handling MatrixParam for top-level resources only?

@soumitra-st I don't quite understand, we are striping the matixParamter during urlCheck and not handling for any specific case. Can you provide more details or example on what you mean?

**Comment by soumitra-st** [comment]
> > > Modify Parser to strip matrix parameter when checking for basePath
> > 
> > 
> > @praveenc7 ,Pinot does not support MatrixParam. Can you elaborate on the context of handling MatrixParam for top-level resources only?
> 
> @soumitra-st I don't quite understand, we are striping the matixParamter during urlCheck and not handling for any specific case. Can you provide more details or example on what you mean?

You are stripping the matrixparams from the URL before, `https://pinot.example.com/file.txt;param1=value1` will behave as `https://pinot.example.com/file.txt` . My questions is, why have `https://pinot.example.com/file.txt;param1=value1` URL? IMO, Pinot does not support MatrixParam, it supports QueryParam .

**Comment by Jackie-Jiang** [comment]
> In addition to the above whitelisted paths, all top files having at least one '.' are allowed. This is likely done to allow access to top-level resource files.

@soumitra-st Do we need to carry-over this behavior? I don't follow why we want to allow such access without going through auth

**Comment by soumitra-st** [comment]
> @soumitra-st Thanks for the example. You’re right that Pinot doesn’t support MatrixParam but instead relies on QueryParam. However, users may unintentionally or maliciously include special characters after matrix-style parameters (;) in URLs, which could pose security risks if not handled properly. cc : @siddharthteotia

@praveenc7, I agree with the security issue. Did you discover this issue from a code/security review or pen testing?

I see one issue. Now https://pinot.example.com/file.txt;param1=value1/blah will be checked as if it is https://pinot.example.com/file.txt and will be executed without AUTH. Is it desirable?

**Comment by soumitra-st** [comment]
> > In addition to the above whitelisted paths, all top files having at least one '.' are allowed. This is likely done to allow access to top-level resource files.
> 
> @soumitra-st Do we need to carry-over this behavior? I don't follow why we want to allow such access without going through auth

@Jackie-Jiang , I checked the git history but could not find why we have both whitelisting (UNPROTECTED_PATHS) and open top-level resources. We can remove the open top-level resources, find the list of top-level files, and add them to the whitelist. Let me know if we should do that; I can create a task.

**Comment by Jackie-Jiang** [comment]
> > > In addition to the above whitelisted paths, all top files having at least one '.' are allowed. This is likely done to allow access to top-level resource files.
> > 
> > 
> > @soumitra-st Do we need to carry-over this behavior? I don't follow why we want to allow such access without going through auth
> 
> @Jackie-Jiang , I checked the git history but could not find why we have both whitelisting (UNPROTECTED_PATHS) and open top-level resources. We can remove the open top-level resources, find the list of top-level files, and add them to the whitelist. Let me know if we should do that; I can create a task.

Agree. I'm not familiar with how these resources are utilized, maybe we can directly remove them.

**Comment by soumitra-st** [comment]
Thanks @praveenc7 for the context in Slack. The gap exposes serious security issue. Approving the PR.

@Jackie-Jiang , we can take up the whitelisting enhancement separately. WDYT?

**Review by soumitra-st — APPROVED** [review]
LGTM

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
