### PR TITLE
bugfix: do not move src ByteBuffer position for LZ4 length prefixed decompress

### PR DESCRIPTION
**Pull request by itschrispeck**
Addresses https://github.com/apache/pinot/issues/12534 

Based on my understanding, calling `_decompressor.decompress(compressedInput, decompressedOutput)` is problematic because it [moves the position](https://javadoc.io/doc/org.lz4/lz4-java/1.6.0/net/jpountz/lz4/LZ4DecompressorWithLength.html#decompress(java.nio.ByteBuffer,%20java.nio.ByteBuffer)) of the src and dest ByteBuffers. It is possible to move the position of the src buffer beyond the limit of the buffer (see issue for details).

The change calls the [same underlying method](https://github.com/lz4/lz4-java/blob/master/src/java/net/jpountz/lz4/LZ4DecompressorWithLength.java#L246), but only moves the position of the dest buffer. The reason why this was a V4 raw index writer/reader version issue is that this only happens with the length prefixed LZ4 library, and this code path is not used for other raw index writer versions.

Testing: Set up a unit test locally, now able to read a previously unreadable segment when loading/iterating through a problematic column using PinotSegmentRecordReader

### CODE REVIEW

**Comment by richardstartin** [comment]
This is a good catch. I have a couple of remarks:
1. It would be good to add a test because this is  a subtle bug that has been hiding in plain sight for over two years, and it could regress in refactoring
2. Whilst I introduced this bug and am a committer, I’m not really involved in the project any more and can only rubber stamp this change.

**Review by richardstartin — APPROVED** [review]

**Comment by Jackie-Jiang** [comment]
Trying to understand the problem better here. Why would it cause problem when the source position is moved? It is allowed for `decompress()` to move the position of the compressed buffer, and it should not break.

**Comment by itschrispeck** [comment]
> Trying to understand the problem better here. Why would it cause problem when the source position is moved? It is allowed for `decompress()` to move the position of the compressed buffer, and it should not break.

I don't think the last bit is always true. While it is allowed to move the position, `lz4_decompress_fast` can move it beyond the source buffer's limit. See this example, the returned bytes `read` value is greater than `src.limit`:

image

There's a note in the [docs](http://ppl.cs.illinois.edu/doxygen/charm/lz4_8c.shtml#fc1e392c915b02d2459c3453bd647b4a):

>The function never writes past the output [buffer](http://ppl.cs.illinois.edu/doxygen/charm/structbuffer.shtml). However, since it doesn't know its 'src' size, it may read past the intended input. Also, because match offsets are not validated during decoding, reads from 'src' may underflow.

I am not sure if the the fast decompressor is the best choice. It may be better to move to the safe decompressor which is already used for non v4 indexes. Doing that would also address this bug.
> [LZ4_decompress_fast()](http://ppl.cs.illinois.edu/doxygen/charm/lz4_8c.shtml#fc1e392c915b02d2459c3453bd647b4a) : **unsafe!** This function used to be a bit faster than [LZ4_decompress_safe()](http://ppl.cs.illinois.edu/doxygen/charm/lz4_8c.shtml#5b433861ebd45cd96e65428febd89929), though situation has changed in recent versions, and now `LZ4_decompress_safe()` can be as fast and sometimes faster than `LZ4_decompress_fast()`. Moreover, LZ4_decompress_fast() is not protected vs malformed input, as it doesn't perform full validation of compressed data. As a consequence, this function is no longer recommended, and may be deprecated in future versions. It's only remaining specificity is that it can decompress data without knowing its compressed size.

**Comment by Jackie-Jiang** [comment]
@itschrispeck Thanks for digging into it! I feel using safe decompressor is the safe go here, and we can get consistent behavior for v2 and v4.

**Comment by Jackie-Jiang** [comment]
+1 on adding a unit test to prevent future regression

**Comment by itschrispeck** [comment]
Updated to use safe decompressor. This will move src to `src.limit()` instead of based on bytes read ([ref](https://github.com/lz4/lz4-java/blob/master/src/java/net/jpountz/lz4/LZ4SafeDecompressor.java#L149)).

I wasn't able to figure out a good way to round trip unit test this. I've added a comment on why the safe decompressor is chosen to hopefully avoid refactoring into the fast decompressor. With more understanding of the LZ4 algorithm I could probably edit some compressed data's bytes to cause this, but given that fast decompressor is deprecated I'd prefer if we can merge this without the test. 

I did a basic validation of the underlying decompress implementations. In general, perf differences are a wash and vary based on host/input:

```
+--------------+------------------------------+--------------+----------------+--------------+--------------+
|Source        |Function Benchmarked          | Total Seconds|  Iterations/sec|  ns/Iteration|  % of default|
+--------------+------------------------------+--------------+----------------+--------------+--------------+
|Normal Text   |LZ4_decompress_safe()         | 140.382024000|          356170|          2807|       100.00%|
|Normal Text   |LZ4_decompress_fast()         | 133.453277000|          374662|          2669|        95.06%|
|              |                              |              |                |              |              |
|Compressible  |LZ4_decompress_safe()         |  28.044312000|         1782892|           560|        19.98%|
|Compressible  |LZ4_decompress_fast()         |  32.404868999|         1542978|           648|        23.08%|
+--------------+------------------------------+--------------+----------------+--------------+--------------+

```

**Pull request merged**
