### PR TITLE
Use _hasNull in the object single column distinct executors.

### PR DESCRIPTION
**Pull request by shenyu0127**
- Fix a bug in NULL ordering.
- Fix a bug in byte type NULL handling (currently `new ByteArray(value)` would throw an exception if `value` is NULL).

Tested in unit tests.

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
Should we consider doing the same trick as primitive data types by tracking a `_hasNull` flag to avoid the extra null handling? That way the behavior is consistent across all data types, and the overall cost should be lower

**Comment by shenyu0127** [comment]
> Should we consider doing the same trick as primitive data types by tracking a `_hasNull` flag to avoid the extra null handling? That way the behavior is consistent across all data types, and the overall cost should be lower

The `_hasNull` flag is a not a clean solution and we want to avoid if possible.

- The `_hasNull` flag needs to be used for primitive data types because the primitive data type sets/priority_queues cannot store NULL.
- The `_hasNull` flag has an issue (if there is NULL, it will always be present in the executor result regardless of the ordering) that needs to be fixed in the upstream handling (DistinctTable).

**Comment by shenyu0127** [comment]
> > Should we consider doing the same trick as primitive data types by tracking a `_hasNull` flag to avoid the extra null handling? That way the behavior is consistent across all data types, and the overall cost should be lower
> 
> The `_hasNull` flag is a not a clean solution and we want to avoid if possible.
> 
> * The `_hasNull` flag needs to be used for primitive data types because the primitive data type sets/priority_queues cannot store NULL.
> * The `_hasNull` flag has an issue (if there is NULL, it will always be present in the executor result regardless of the ordering) that needs to be fixed in the upstream handling (DistinctTable).

Had an offline chat with @Jackie-Jiang  and we aligned to use `_hasNull` mainly for performance (avoid additional null checks in the comparators).

**Review by Jackie-Jiang — APPROVED** [review]
LGTM! Can you resolve the conflict in the test?

**Comment by shenyu0127** [comment]
> LGTM! Can you resolve the conflict in the test?

Thank you for the review and approval! Rebased and force-pushed.

**Pull request merged**
