### PR TITLE
[hotfix] semi-join opt

### PR DESCRIPTION
**Pull request by walterddr**
semi-join opt should not happen b/c we don't support

### CODE REVIEW

**Review by siddharthteotia — APPROVED** [review]

**Comment by 61yao** [comment]
Are we able to cover this in unit test? 
pinot-query-planner/src/main/java/org/apache/calcite/rel/rules/PinotQueryRuleSets.java
I accidentally found this bug when I was playing around semi join test. 
I feel we should have caught this before integration test

**Comment by walterddr** [comment]
> Are we able to cover this in unit test? pinot-query-planner/src/main/java/org/apache/calcite/rel/rules/PinotQueryRuleSets.java I accidentally found this bug when I was playing around semi join test. I feel we should have caught this before integration test

no i didn't add a operator test b/c i don't wanna create a rebase issue for https://github.com/apache/pinot/pull/9775. we can incorporate in that PR

**Comment by 61yao** [comment]
> > Are we able to cover this in unit test? pinot-query-planner/src/main/java/org/apache/calcite/rel/rules/PinotQueryRuleSets.java I accidentally found this bug when I was playing around semi join test. I feel we should have caught this before integration test
> 
> no i didn't add a operator test b/c i don't wanna create a rebase issue for #9775. we can incorporate in that PR

I meant PinotQueryRuleSets not operator test.

**Comment by walterddr** [comment]
> I meant PinotQueryRuleSets not operator test.

good point. we don't have test for specific rules. we should add that next

**Pull request merged**
