### PR TITLE
Support INSERT INTO table FROM inputDirURI statement

### PR DESCRIPTION
**Pull request by xiangfu0**
Support INSERT INTO table FROM inputDirURI statement

1. Parse the query with the table name and directory URI along with a list of options for the ingestion job.
2. Call controller minion task execution API endpoint to schedule the task on minion
3. Response has the schema of table name and task job id.
Syntax:
```
INSERT INTO [database.]table FROM FILE dataDirURI OPTION ( k=v ) [, OPTION (k=v)]*
```
E.g.
```
INSERT INTO "baseballStats"
FROM FILE 's3://my-bucket/public_data_set/baseballStats/rawdata/'
OPTION(taskName=myTask-s3)
OPTION(input.fs.className=org.apache.pinot.plugin.filesystem.S3PinotFS)
OPTION(input.fs.prop.accessKey=my-key)
OPTION(input.fs.prop.secretKey=my-secret)
OPTION(input.fs.prop.region=us-west-2)
```

Sample:
image

### CODE REVIEW

**Comment by amrishlal** [comment]
This query appears to be processed on the Controller side. Would the query still work if it is sent to Broker API? If not, then can the Broker forward the query to the controller for processing?

**Comment by xiangfu0** [comment]
Good point. I'm testing it from the UI, so it's simpler to put the logic in controller. The same logic can definitely be moved to broker request handler.

Just the controller call need to be sent from broker, which requires some code refactor to extract some code logic from Pinot-controller to Pinot-common.

**Comment by kishoreg** [comment]
+1 on supporting this call on the broker

**Comment by xiangfu0** [comment]
rework on : https://github.com/apache/pinot/pull/8557

**Pull request closed without merging**
