### PR TITLE
Remove JsonUtils dependency due to classpath issues

### PR DESCRIPTION
**Pull request by KKcorps**

### CODE REVIEW

**Review by snleee — APPROVED** [review]

**Comment by snleee** [comment]
Adding more context on this PR:

- We have seen that multiple versions of `JsonUtils` are pulled. (While having the same name space, the parameter's class namespace are different due to shading).
- This is a short/mid term fix where we remove `JsonUtils` dependency from Kinesis library to resolve the dependency conflict.

**Comment by Jackie-Jiang** [comment]
@snleee @KKcorps `JsonUtils` is a pinot util class. How is it possible to pull multiple versions of it?

**Comment by Jackie-Jiang** [comment]
Does that mean we cannot use any class under `pinot-spi`?

**Comment by Jackie-Jiang** [comment]
@xiangfu0 I'm not very familiar with shading, but I don't think this is the correct fix because basically this means we cannot use any utils that pulls external dependencies. Can you also provide your opinion?

**Comment by snleee** [comment]
This is more for short term fix. We can revert this after we resolve the shading issue. Ideally, we should have a single definition of `JsonUtils` but it looks that it not easy to achieve. Let's discuss on this.

**Comment by gortiz** [comment]
There are two different issues:
- We have JsonUtils several times in the classpath with the same package. Luckily, the correct one is loaded first.
- The plugins shade jackson using their package prefix. That means that when they call public spi that use jackson, they use their own package. For example, they call `<apache pinot package>.JsonUtils.stringToObject(String, <their-package-prefix>.TypeReference)`, which does not exist.

That later problem is the one that affected us. The problem here is that by adding jackson arguments and results to our spi methods, we are indicating that jackson should not be shaded, when in fact jackson is one the main package we want to shade due to incompatibilities in the classpath.

**Pull request merged**
