### PR TITLE
Move ControllerRequestURLBuilder to SPI

### PR DESCRIPTION
**Pull request by saurabhd336**
ControllerRequestURLBuilder provides certain util functions that are needed across modules hence moving this and its dependencies to to pinot-spi.
Follow up PR that uses ControllerRequestURLBuilder in pinot-clients https://github.com/apache/pinot/pull/8467

### CODE REVIEW

**Review by xiangfu0 — APPROVED** [review]
lgtm!

**Comment by richardstartin** [comment]
@saurabhd336 can you explain the motivation in the PR description please (you can delete the template).

**Comment by saurabhd336** [comment]
Done @richardstartin. @xiangfu0 had some other dependencies on this PR. I wanted to be able to use the util class in pinot-clients for https://github.com/apache/pinot/pull/8467

**Comment by xiangfu0** [comment]
Thanks @saurabhd336 
I also need this in https://github.com/apache/pinot/pull/8557

**Pull request merged**
