### PR TITLE
add tooltip and modal for table status

### PR DESCRIPTION
**Pull request by jadami10**
## Description

It's always bothered me how difficult it is to tell why a table with hundreds of segments, even when they're all "good" shows up as "bad". So this adds a tooltip and a modal that explains why.

This is a bit of a big change for what it's doing, so i'm happy for feedback on a better approach.

I need to test this on a bigger cluster internally, but let me know if this is desirable before I do that.
image
image

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
This is super cool!

I would suggest always putting the whole `segment -> instance state map` into the tooltip. With in the screenshot I still cannot tell which segment has inconsistent EV vs IS.
E.g.
```
{
  "segment-0": {
    "server-0": "ONLINE",
    "server-1": "ERROR"
  }
}
```

Also, when segment count does not match in EV vs IS, it would be helpful to show the mismatching segments in the tooltip

**Comment by jadami10** [comment]
I've updated it to show full diffs.

Here's what it looks like now when they're not equal
image


Here's what it looks like when segments are missing
image
image

I changed the meetupRsvp table to do 2 rows per segment so i could get a bunch of segments, then took the server offline. Here's what it looks like with 258 bad segments in the diff. The lagginess is because mov -> gif was too big, I had to lower it to 3 fps. It's very fast.
bad_segments

**Comment by Jackie-Jiang** [comment]
This is awesome! @shahsank3t Can you please help review this? The example looks good to me

**Review by shahsank3t — APPROVED** [review]
awesome work on this.
+1 Looks good to me!

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
