### PR TITLE
Separate the metric for records filtered during ingesiton

### PR DESCRIPTION
**Pull request by navina**
* Introduce new metric for filtered records - `REALTIME_ROWS_FILTERED`
* Include decoding error count in `ROWS_WITH_ERRORS`

Labels: `backward-incompat` , `observability`

## Release Notes
TBD once changes are approved.

### CODE REVIEW

**Comment by navina** [comment]
cc: @npawar

**Comment by navina** [comment]
@Jackie-Jiang / @snleee : review pls?

**Comment by kishoreg** [comment]
Is REALTIME_ROWS_FILTERED referring to rows filtered during query or ingestion

**Comment by navina** [comment]
> Is REALTIME_ROWS_FILTERED referring to rows filtered during query or ingestion

during ingestion

**Review by npawar — APPROVED** [review]
sumMing up my understanding:
REALTIME_CONSUMPTION_EXCEPTIONS - stream transient/permanent exceptions

ROWS_WITH_ERRORS - indexing exceptions, transformation exceptions and decoding exceptions
INVALID_REALTIME_ROWS - decoding exceptions
REALTIME_ROWS_FILTERED - rows skipped by filter config
INCOMPLETE_REALTIME_ROWS_CONSUMED - incomplete rows

REALTIME_ROWS_CONSUMED - row successfully consumed


Only comment I have is, can we add a granular metric for transformation exceptions and inedxing exceptions as well? This was we'll have every individual exception and the overall too. I don't know if there's a better way to do this instead of adding new metrics (probably adding labels).

But this PR is good to go.

**Pull request merged**
