### PR TITLE
Fix bug to return validDocIDsMetadata from all servers

### LINKED ISSUE #12423: CompletionServiceHelper's doMultiPostRequest returns whenever 1 server responds instead of waiting for all
labels:
bug

This seems to be associated with this change #12275 

When using UpsertCompaction, we make a `doMultiPostRequest` to all the servers for a table with the list of validDocIds. But seems it is not working as expected. The API only returns results from 1 server at a time. 

The logs always shows this:
```
Finished reading information for table: TABLE_REALTIME with 1/4 server responses
```

I checked all the 4 servers received the request in this scenario and all were processing fine. Just that `CompletionServiceHelper` seems to be processing only 1. When I hit the controller API multiple times, each time the respond comes from different servers showing that each server individually works fine. This way UpsertCompaction is processing segments of only 1 server at a time.

cc @snleee

### PR DESCRIPTION
**Pull request by tibrewalpratik17**
label:
 `bugfix`
 
Fixes #12423 

We were sending `serverToEndpoints` mapping instead of `endpointsToServer` which is expected by CompletionService. That's why CompletionService was always returning 1 server's response as it was having null as the only key in map and returning response of the last server it receives overwriting the response of previous server(s) always.

The impact of this bug was that getValidDocIdMetadata endpoint was always returning results from one server instead of the number of servers the table is actually hosted on. This affects UpsertCompaction task too as it now processes the segments of any 1 random server at a time instead of all.

Another bug fix from #12445 

Currently, this endpoint `tables/{tableName}/validDocIdsMetadata` returns the validDocID metadata for the same segment multiple times (equal to number of replicas).

This causes issues with UpsertCompaction task too as the same segment starts getting processed multiple times (for deletion / compaction).

This patch dedupes the response of the API itself which is implicitly used by UpsertCompactionTaskGenerator too.

### CODE REVIEW

**Review by ankitsultana — APPROVED** [review]
Good catch. @tibrewalpratik17 : can you also add what was the impact of this bug in the description?

**Comment by tibrewalpratik17** [comment]
@snleee can you take a look at this fix for the tagged issue?

**Comment by snleee** [comment]
@tibrewalpratik17 can we combine this pr with https://github.com/apache/pinot/pull/12445?

**Review by snleee — APPROVED** [review]
LGTM! Thanks for catching the issue.

**Pull request merged**
