### PR TITLE
bind to whichever port is available

### PR DESCRIPTION
**Pull request by richardstartin**
## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Review by walterddr — APPROVED** [review]
looking good. but why is CI still failing on the same?

**Comment by richardstartin** [comment]
@walterddr I don’t think there are any available ports, but I don’t know why that is if why it’s changed.

**Comment by Jackie-Jiang** [comment]
Seems like reusing the JVM for multiple tests that use `HttpHandler` is causing the issue. This can be reproduced locally. The CI just started failing might because it didn't share JVM across multiple tests before. #7699 should be the valid fix

**Comment by richardstartin** [comment]
@Jackie-Jiang I think we just need to be sure we release the ports we use, then this sort of thing won't happen and we won't need to rely on JVM shutdown for the release to take place.

**Pull request closed without merging**
