### PR TITLE
Upgrade spark from 3.2 to 3.5

### PR DESCRIPTION
**Pull request by gortiz**
This PR tries to blindly update from Spark 3.2.4 to 3.5.0.

See https://github.com/apache/pinot/issues/11701

### CODE REVIEW

**Comment by gortiz** [comment]
Marked as ready to review. Last commit seems to be running correctly but failed in what it looks a flaky test.

The main issue here is what should we do with the name of module `pinot-batch-ingestion-spark-3.2`. In this PR we don't use 3.2 but 3.5. These versions seem to be backward compatible, so semantics should be the same, but the name of the project may be misleading.

**Review by xiangfu0 — COMMENTED** [review]
Please rebase, overall lgtm.

**Review by xiangfu0 — APPROVED** [review]

**Comment by xiangfu0** [comment]
can you rebase the PR?

**Comment by gortiz** [comment]
Rebased

**Comment by mcvsubbu** [comment]
@gortiz is bumping to log4j-slf4j2 absolutely necessary? Can we revert that?

The reason is that this pulls in later version of log4j library (like you have changed), and they seem to have thread contention at high loads (we have seen that in LinkedIn multiple times).

**Comment by gortiz** [comment]
I've replied in https://github.com/apache/pinot/pull/11903#issuecomment-1784637051. The TL;DR: is that it was necessary in order to correctly use the `slf4j` version Spark 3.5 expects in the classpath.

As you can see in https://github.com/apache/pinot/pull/11903, spark 3.5 tests fail when using older slf4j versions. As explained in my comment we could:
- Keep `log4j2` in 2.17.1 and use `log4j-slf4j18`, which _may_ support `slf4j` v2. I don't like this approach, but may be the easiest to implement.
- Keep `log4j2` in 2.20 (or update it to 2.21) and use `log4j-slf4j2`. The contention problem is new to me, we should report it to log4j2 trying to fix it. Keep using log4j2 in v 2.17.1 (released 2 years ago) is problematic. Imagine a new vulnerability is found in that version, we would like to be able to upgrade to the newest version that fixes it.
- Try to make the test work somehow. This is my least preferred option because it would just silence a possible runtime error.

**Pull request merged**
