### PR TITLE
Exclude unnecessary dependencies in pinot-clients 

### PR DESCRIPTION
**Pull request by abhioncbr**
As per the [issue](https://github.com/apache/pinot/issues/11507), removing unnecessary dependencies in pinot-clients

### CODE REVIEW

**Comment by abhioncbr** [comment]
@cyrilou242, can you please verify and confirm that exclusions are good? Thanks

**Comment by cyrilou242** [comment]
Hey @abhioncbr I'm not sure this is a good approach in terms of maintainability: 
- this makes the pom very complex
- dependencies in `common` and `core` may change. I fear clients exclusion will not be updated accordingly
- clients developer may be tempted to use classes of the `common` and `core` package that won't work at runtime because some dependencies will have been excluded

I'm not a maintainer of pinot so I don't have a strong opinion but I think it'd be better to first discuss potential solutions in the issue.

**Review by xiangfu0 — APPROVED** [review]

**Comment by abhioncbr** [comment]
> Hey @abhioncbr I'm not sure this is a good approach in terms of maintainability:
> 
> * this makes the pom very complex
> * dependencies in `common` and `core` may change. I fear clients exclusion will not be updated accordingly
> * clients developer may be tempted to use classes of the `common` and `core` package that won't work at runtime because some dependencies will have been excluded
> 
> I'm not a maintainer of pinot so I don't have a strong opinion but I think it'd be better to first discuss potential solutions in the issue.

Thanks for the feedback, @cyrilou242, I agree this is not a good solution, and you already outlined the drawbacks. 
However, in my understanding, we don't have much of options here, One is to add the exclusion, and the other is either to copy the used code into the java client itself or create a separate submodule and move the dependency code into the new submodule. Please suggest if you have some other options in mind.

**Comment by Jackie-Jiang** [comment]
@abhioncbr We have to revert his PR because it breaks the JDBC client (unfortunately this PR was included in release 1.0, but the fix was not..) Can you help re-do this PR with a test on the `pinot-client`? Seems we don't have test on them because the JDBC connector cannot even be instantiated after this PR

**Pull request merged**
