### PR TITLE
skip retry very old rebalance jobs

### PR DESCRIPTION
**Pull request by klsince**
This PR tries to enhance the RebalanceChecker a bit to skip failed rebalance jobs that's very old.

There could be edge cases that rebalance job failed and left a failure job status in ZK, but the table got rebalanced with server restarts or other cluster operations, leaving this failure job status in ZK for a long time until it's cleaned up (by a cleanup mechanism that's size based not time based). So when table got imbalanced like during planned maintenance, the checker might kick off rebalance unexpectedly. 

So adding a new config `skipRetryTimeoutInMs` for rebalance job to skip retrying old jobs. The config is 86400000 (i.e. 1day) by default.

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
I'd rather enhance the cleanup to also clean up old tasks so that this mechanism is general.
Will the re-run cause problem? Rebalance itself should be idempotent, and rerunning it should return immediately if it is already balanced

**Comment by klsince** [comment]
> Will the re-run cause problem? Rebalance itself should be idempotent, and rerunning it should return immediately if it is already balanced 

Right, rerunning returned as noop immediately. But it didn't post any job status if it's noop, so RebalanceChecker would continue to see the failure job status and retry again, entering a loop until either 1) the job status is cleaned up; 2) the table actually gets imbalanced and causes a real rebalance to happen, when new job status is posted overriding the failure status.

Enhancing the cleanup mechanism would not work due to the edge case of noop as above. Because cleanup of job status is done while posting new job status. So if it's noop, no job status is posted at all, and no cleanup happens.

Alternatively, we can post job status even for noop. Then, the noop status can override the old failure status.

**Comment by Jackie-Jiang** [comment]
Based on the analysis, the root problem is that the no-op rerun won't update the job status. We need to fix that

**Comment by klsince** [comment]
No problem, will fix that instead, and then no need for this fix. Closing for now

**Pull request closed without merging**
