### PR TITLE
[Dependency] Cleanup unnecessary dependencies and exclusions

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Also add the following libraries to the enforcer banned list:
- `org.slf4j:slf4j-log4j12`: Use `org.slf4j:slf4j-reload4j`
- `log4j:log4j`: Use `org.apache.logging.log4j:log4j-core`
- `org.apache.logging.log4j:log4j-slf4j-impl`, `org.slf4j:slf4j-log4j12`, `org.slf4j:slf4j-reload4j`: Use `org.apache.logging.log4j:log4j-slf4j2-impl`
- `com.sun.jersey`: Use `org.glassfish.jersey`
- `org.apache.hadoop.thirdparty:hadoop-shaded-protobuf_3_7`: Use `org.apache.hadoop.thirdparty:hadoop-shaded-protobuf_3_21`

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
[Help wanted] I've been running into the following issue in quick-start:
```
java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/yaml/snakeyaml/internal/Logger (wrong name: org/yaml/snakeyaml/internal/Logger)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) ~[?:?]
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) ~[?:?]
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) ~[?:?]
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) ~[?:?]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at org.yaml.snakeyaml.TypeDescription.<clinit>(TypeDescription.java:43) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:60) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:50) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.yaml.snakeyaml.Yaml.<init>(Yaml.java:64) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.BootstrapTableTool.setupOfflineData(BootstrapTableTool.java:217) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.BootstrapTableTool.bootstrapOfflineTable(BootstrapTableTool.java:194) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.BootstrapTableTool.execute(BootstrapTableTool.java:104) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.admin.command.QuickstartRunner.bootstrapTable(QuickstartRunner.java:232) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.Quickstart.execute(Quickstart.java:86) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.admin.command.QuickStartCommand.execute(QuickStartCommand.java:178) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.Command.call(Command.java:33) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.Command.call(Command.java:29) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at picocli.CommandLine.access$1500(CommandLine.java:148) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at picocli.CommandLine.execute(CommandLine.java:2174) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:173) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
        at org.apache.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:204) ~[pinot-all-1.3.0-SNAPSHOT-jar-with-dependencies.jar:1.3.0-SNAPSHOT-4e5a6a24b963fc0bdbbbb76e42cb7c1af4575132]
```

**Comment by Jackie-Jiang** [comment]
Find a similar [issue](https://github.com/prometheus/jmx_exporter/issues/802), and borrowed the solution from there

**Review by xiangfu0 — APPROVED** [review]

**Comment by jadami10** [comment]
@Jackie-Jiang, what was the intention of this PR? Like why did we do it?

On our end, removing exclusions has suddenly brought in transitive dependencies into the uber jar that are conflicting with our own plugins. We can probably work around it, but I want to understand why we're making such large changes to the dependency structure.

**Comment by Jackie-Jiang** [comment]
@jadami10 It is mostly for easier dependency management, and avoid unnecessary repeated declarations.
Which exclusion do you find necessary? Most of the removed exclusions should be redundant, where the excluded dependency is actually defined. Or are you overriding the version of some dependency? If so, can you try modifying them in the dependency management section? Then the dependency should be resolved to the desired version.

**Comment by jadami10** [comment]
I believe in our case the issue is that hadoop came with `curator`. And we use `curator` in a plugin as well. So the version in our plugin then clashed with the version hadoop brought in

cc @dang-stripe who has the specific details/versions

**Comment by Jackie-Jiang** [comment]
@jadami10 @dang-stripe You should be able to override `curator.version` property to avoid the version conflict.

**Comment by dang-stripe** [comment]
@Jackie-Jiang curator was pulled in by hadoop-common which some pinot modules depended on so it showed up in our pinot uberjar whereas it didn't exist before. the uberjar is at the beginning of our classpath before our plugins so the version was getting loaded first.

```
[INFO] -------------------< org.apache.pinot:pinot-parquet >-------------------
[INFO] org.apache.pinot:pinot-parquet:jar:1.2.0-SNAPSHOT
[INFO] \- org.apache.hadoop:hadoop-common:jar:3.3.6:compile
[INFO]    \- org.apache.hadoop:hadoop-auth:jar:3.3.6:compile
[INFO]       \- org.apache.curator:curator-framework:jar:5.2.0:compile

[INFO] --------------------< org.apache.pinot:pinot-tools >--------------------
[INFO] org.apache.pinot:pinot-tools:jar:1.2.0-SNAPSHOT
[INFO] \- org.apache.hadoop:hadoop-common:jar:3.3.6:compile
[INFO]    \- org.apache.hadoop:hadoop-auth:jar:3.3.6:compile
[INFO]       \- org.apache.curator:curator-framework:jar:5.2.0:compile
```

we added back the exclusion for `hadoop-common` in `pinot-distribution` to work around it instead so it'd get excluded in the uberjar.

**Pull request merged**
