### PR TITLE
Parallelize segment index init and building

### PR DESCRIPTION
**Pull request by JohnTortugo**
I'm from a Microsoft team working with LinkedIn engineers to improve Pinot performance. In a previous talk with @mayankshriv, he said that segment creation is slow and if we could take a look to improve that. CPU profiling, using synthetic data, for the segment creation code, produced the following flame graph:

CPU Hotspots [Full resolution image](https://cesarshare.blob.core.windows.net/pinot-investigation/SegmentCreation-Flames.png)

Basically, segment creation is made of two roughly equal parts: init & build. Both methods are very similar in the sense that they have a main loop that iterates over rows in the input data doing some transformation on each of them. This PR introduces two main changes:

1) A new Pinot-perf benchmark used for benchmarking segment creation performance.

2) The parallelization of the init->gatherStats and build methods mentioned above. The main loop of each method was parallelized using a technique called [DSWP](https://liberty.princeton.edu/Publications/micro05_dswp.pdf) and we made use of [Disruptor RingBuffer](https://github.com/LMAX-Exchange/disruptor) to implement thread communication.

### Original code

```
# Run progress: 0.00% complete, ETA 00:07:00
# Fork: 1 of 2
# Warmup Iteration   1: 31097.686 ms/op
# Warmup Iteration   2: 26007.428 ms/op
# Warmup Iteration   3: 26816.007 ms/op
Iteration   1: 25951.170 ms/op
Iteration   2: 26076.096 ms/op
Iteration   3: 26045.939 ms/op

# Run progress: 50.00% complete, ETA 00:05:19
# Fork: 2 of 2
# Warmup Iteration   1: 31711.546 ms/op
# Warmup Iteration   2: 26587.875 ms/op
# Warmup Iteration   3: 27360.283 ms/op
Iteration   1: 26208.574 ms/op
Iteration   2: 26316.409 ms/op
Iteration   3: 26194.492 ms/op


Result "org.apache.pinot.perf.BenchmarkSegmentCreation.segmentCreationFromCSV":
  26132.113 ±(99.9%) 369.912 ms/op [Average]
  (min, avg, max) = (25951.170, 26132.113, 26316.409), stdev = 131.914
  CI (99.9%): [25762.202, 26502.025] (assumes normal distribution)


# Run complete. Total time: 00:10:42

Benchmark                                     Mode  Cnt      Score     Error  Units
BenchmarkSegmentCreation.segmentCreationFromCSV  avgt    6  26132.113 ± 369.912  ms/op
```

### New code

```
# Run progress: 0.00% complete, ETA 00:03:20
# Fork: 1 of 2
# Warmup Iteration   1: 23004.364 ms/op
# Warmup Iteration   2: 19380.296 ms/op
# Warmup Iteration   3: 20914.349 ms/op
# Warmup Iteration   4: 19469.886 ms/op
# Warmup Iteration   5: 19461.024 ms/op
Iteration   1: 19523.648 ms/op
Iteration   2: 19582.673 ms/op
Iteration   3: 19409.540 ms/op
Iteration   4: 19419.701 ms/op
Iteration   5: 19386.130 ms/op

# Run progress: 50.00% complete, ETA 00:03:20
# Fork: 2 of 2
# Warmup Iteration   1: 23344.723 ms/op
# Warmup Iteration   2: 19335.702 ms/op
# Warmup Iteration   3: 20535.619 ms/op
# Warmup Iteration   4: 19512.260 ms/op
# Warmup Iteration   5: 19461.238 ms/op
Iteration   1: 19510.350 ms/op
Iteration   2: 19453.281 ms/op
Iteration   3: 19444.863 ms/op
Iteration   4: 19399.972 ms/op
Iteration   5: 19380.142 ms/op


Result "org.apache.pinot.perf.BenchmarkSegmentCreation.segmentCreationFromCSV":
  19451.030 ±(99.9%) 101.684 ms/op [Average]
  (min, avg, max) = (19380.142, 19451.030, 19582.673), stdev = 67.258
  CI (99.9%): [19349.346, 19552.714] (assumes normal distribution)


# Run complete. Total time: 00:06:41

Benchmark                                        Mode  Cnt      Score     Error  Units
BenchmarkSegmentCreation.segmentCreationFromCSV  avgt   10  19451.030 ± 101.684  ms/op
```

### CODE REVIEW

**Review by mayankshriv — COMMENTED** [review]
Thanks for taking the initiative to improve segment generation time. A few high level questions:
- Is there any impact on memory-usage/GC? If so, would be good to measure.
- For the most part in the code, we use long living executor service to reuse threads from, so that we don't end up allocating too many threads. Would it be possible to do the same here? 

Side note, this code is executed in realtime servers, as well as in offline compute (spark/MR).

**Comment by mayankshriv** [comment]
Tagging @siddharthteotia @Jackie-Jiang for review.

**Comment by mcvsubbu** [comment]
Garbage collection during segment build has been a bigger problem for us than the segment build itself -- in the realtime path. In the offline path, where segments are built in hadoop/spark, we have not had issues with GC or performance.

Here is a prototype that I had done a while ago, using a columnar segment builder reduced GC significantly.

https://github.com/apache/incubator-pinot/issues/4036

Please use a similar technique and post GC results for some use cases where you hit performance problems (yes, unfortunately, the amount of garbage depends on the kind of columns you have -- I suspect performance also goes the same way).

In which scenario are you facing performance problems?

Lastly, if you could please add a short paragraph outlining your approach, that will help reviewers. Thanks.

**Comment by JohnTortugo** [comment]
Thank you @mayankshriv, @mcvsubbu for reviewing. I'll do some benchmarking to see assert if/how much heap usage increased with the changes I'm proposing.

**Comment by mcvsubbu** [comment]
@JohnTortugo  I updated the link in the issue to point to my fork
https://github.com/apache/incubator-pinot/issues/4036
https://github.com/mcvsubbu/incubator-pinot/commit/c866d9130a5ceddb7a25c3235d605e503e91e13c
The work was done a while ago, so the changes will not apply as is. But you can get an idea of what is consuming heap memory and how to save it.
@snleee  is also interested in contributing here.

**Comment by mcvsubbu** [comment]
@JohnTortugo can you elaborate on where you observed the performance problem? Was it during offline ingestion or in realtime pinot?

**Comment by JohnTortugo** [comment]
@mcvsubbu - I was told by @mayankshriv that this part of Pinot was slow. @mayankshriv - can you please answer @mcvsubbu question about in which situation is the segment creation code slow?

**Comment by mcvsubbu** [comment]
@JohnTortugo please ping me via slack, and we can discuss further. I discussed with @mayankshriv  also, and we concur that reducing garbage collection is the first order of business. We have not observed performance problems in this area, only GC issues when this happens. We will gladly take any performance improvements, however.
The prototype that I had done with columnar segment build yielded both performance as well as GC improvements. Can you please take that up?

**Comment by JohnTortugo** [comment]
Hi @mayankshriv @mcvsubbu - after your reviews (and talking privately on Slack) I understand that segment creation execution time isn't a pain point; memory consumption is the real pain point of this part of Pinot. Nonetheless, the proposed change helps reduce segment creation wall time. My question then is: do you think the contribution of this PR is valuable and, if so, what the next step forward is, or should I just close the PR?

@mcvsubbu - The amount of time allotted for me to work on Pinot this quarter is almost over; I can't take over your work for reducing memory allocation at this time.

**Pull request closed without merging**
