### PR TITLE
Clean up CaseTransformFunction::constructStatementListLegacy.

### PR DESCRIPTION
**Pull request by shenyu0127**
This is a follow-up cleanup for https://github.com/apache/pinot/pull/11328, which is released in Pinot 1.0.

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
Let's not clean it up now. Broker side is just upgraded. If somehow people deploy server first, this query will fail. Let's wait until next release

**Comment by shenyu0127** [comment]
> If somehow people deploy server first

Is this possible? I thought the deployment order was always controller -> broker -> server.

**Comment by Jackie-Jiang** [comment]
@shenyu0127 Ideally user should not do that, but it would be good to leave longer migration window. Currently broker is still running the old format, so it is safer for server to support both for a release.

**Comment by shenyu0127** [comment]
Yes, it is safe to only include the broker side change in the next release and check in this PR after next release.

Converted the PR to draft.

**Comment by shenyu0127** [comment]
@Jackie-Jiang please merge the PR whenever you think is right.

**Review by Jackie-Jiang — APPROVED** [review]
Since 1.0 is already released, we can remove it now

**Pull request merged**
