### PR TITLE
upgrade netty to 4.1.74-Final due to security vulnerability 

### PR DESCRIPTION
**Pull request by GSharayu**
Linkedin internal elr-build is seeing some security vulnerabilities around netty version 4.1.60-Final.
This PR upgrades netty version to 4.1.74-Final due to security vulnerabilities found in netty version 4.1.60 upgraded as part of  #8307

### CODE REVIEW

**Comment by richardstartin** [comment]
This duplicates #8298

**Comment by GSharayu** [comment]
> This duplicates #8298

I think the author is seeing some build issues around pinot-pulsar dependencies

**Review by jasperjiaguo — APPROVED** [review]
LGTM, thanks for fixing this! I'm wondering if we can also use `<netty.version>` in `pinot-pulsar/pom.xml` ?

**Review by jackjlli — APPROVED** [review]

**Comment by richardstartin** [comment]
> > This duplicates #8298
> 
> I think the author is seeing some build issues around pinot-pulsar dependencies and might leave working on the PR

Yes, I see.

Unrelatedly,  LICENSE-binary file needs updating.

**Review by siddharthteotia — APPROVED** [review]

**Comment by pjfanning** [comment]
This resolves https://github.com/apache/pinot/issues/8297

**Pull request merged**
