### PR TITLE
Removing direct dependencies on `commons-logging` and replacing with `jcl-over-slf4j`

### PR DESCRIPTION
**Pull request by timveil**
This PR works to remove all direct and transitive dependencies on `commons-logging` due to well documented class-loading issues and lack of active development.  In places where `commons-logging` was directly referenced, the dependency was replaced by `jcl-over-slf4j` to maintain compatability.

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
This is great! Can you also doublecheck if the new built repo doesn't have `commons-logging` pulled (check `.m2` folder)

**Comment by timveil** [comment]
> This is great! Can you also doublecheck if the new built repo doesn't have `commons-logging` pulled (check `.m2` folder)

what repo are you referring to?

**Comment by Jackie-Jiang** [comment]
> what repo are you referring to?

Sorry for the confusion. I think the intention for this PR is to remove `commons-logging` dependency completely and replace it with `jcl-over-slf4j`. Can you verify if this is the case by building the pinot project, and check if it doesn't pull `commons-logging` from maven?

**Comment by timveil** [comment]
> > what repo are you referring to?
> 
> Sorry for the confusion. I think the intention for this PR is to remove `commons-logging` dependency completely and replace it with `jcl-over-slf4j`. Can you verify if this is the case by building the pinot project, and check if it doesn't pull `commons-logging` from maven?

Yes I was able to verify this using IntelliJ + maven.  In Intellij, after the changes, `commons-logging` no longer appears in any module or as an "External Library".  I also verified this by searching the effective pom and looking at the build output.

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
