### PR TITLE
Fix the null pointer exception for segment assignment strategy in reassigning tiers (Table rebalance) 

### PR DESCRIPTION
**Pull request by GSharayu**
The segment assignment strategy was not getting set during rebalance tiers. 
As mentioned in comment: https://github.com/apache/pinot/pull/9309#discussion_r1018496195

This code handles the null pointer exception and inits the assignment strategy with default config if not set 
Reference PR [Introduce Segment AssignmentStrategy Interface](https://github.com/apache/pinot/pull/9309)
#9309

### CODE REVIEW

**Comment by GSharayu** [comment]
@snleee Please review

**Review by snleee — COMMENTED** [review]
After I looked into a bit more detail, we can actually reproduce the issue under the following:

So the edge case would happen when 
1. rebalance on real-time table
2. no COMPLETED instance partition is provided
3. sotedTier, tierInstancePartitionMap is configured (which means that we have tier tenants but no COMPLETED tenants)

I think that we have 2 behaviors to choose from:
1. Keep the default behavior to be assign all segments to CONSUMING after rebalance (fall back to consuming rebalance since CONSUMING instancePartition must be available for real-time table)
2. Move all COMPLETED segments to Tiers after rebalance

Given that this is a very rare edge case scenario, I would prefer to go with the option 1 for simplicity. We can improve the rebalance behavior when we have the clear idea if we really need to configure tiers without COMPLETED tenant (We can get away this by one of tiers to be COMPLETED...)

@klsince @Jackie-Jiang  Do you guys have a particular preference?

From `RealtimeNonReplicaGroupTieredSegmentAssignmentTest:L264`, Try to add the following line to reproduce the null pointer exception:
```
    // Rebalance without COMPLETED instance partitions and without tierInstancePartitions again should change the
    // segment assignment back
    Map<InstancePartitionsType, InstancePartitions> noRelocationInstancePartitionsMap = new TreeMap<>();
    noRelocationInstancePartitionsMap.put(InstancePartitionsType.CONSUMING,
        _instancePartitionsMap.get(InstancePartitionsType.CONSUMING));
    assertEquals(_segmentAssignment.rebalanceTable(newAssignment, noRelocationInstancePartitionsMap, null, null,
        new BaseConfiguration()), currentAssignment);

    // ADD THIS PART FOR REPRODUCING THE NULL POINTER EXCEPTION
    assertEquals(_segmentAssignment.rebalanceTable(currentAssignment, noRelocationInstancePartitionsMap, _sortedTiers, _tierInstancePartitionsMap,
        new BaseConfiguration()), newAssignment);

```

**Comment by snleee** [comment]
To summarize the comment:

1. Let's make sure that we guarantee `segmentAssignmentStrategy` to be non-null in `RealtimeSegmentAssignment`
2. We should decide the rebalance behavior for the edge case above.

**Comment by klsince** [comment]
Thanks for digging into this issue, @GSharayu @snleee !

> ... we can enforce that COMPLETED instance partition needs to be configured if Tier is used...
> ... We can improve the rebalance behavior when we have the clear idea if we really need to configure tiers without COMPLETED tenant.

I didn't know there is need to configure a COMPLETED tenant. I see tenants are usually named like DefaultTenant_OFFLINE or DefaultTenant_REALTIME for different table types, as well as in the local test I did. Is the `DefaultTenant_REALTIME` used as CONSUMING and COMPLETED tenants for RT table by default? Feel free to point me to docs about those if any.

> 2. Move all COMPLETED segments to Tiers after rebalance

IIUC, this seems what I was assuming to happen: to move COMPLETED segments to new tier if they matches the selection criteria. And leave CONSUMING and other non-matching COMPLETED segments to the default tenant configured for the REALTIME table (DefaultTenant_REALTIME by default).

**Comment by npawar** [comment]
> IIUC, this seems what I was assuming to happen: to move COMPLETED segments to new tier if they matches the selection criteria. And leave CONSUMING and other non-matching COMPLETED segments to the default tenant configured for the REALTIME table (DefaultTenant_REALTIME by default).

this discussion is not very clear to me, but is this is the conclusion, then lgtm
```
IIUC, this seems what I was assuming to happen: to move COMPLETED segments to new tier if they matches the selection criteria. And leave CONSUMING and other non-matching COMPLETED segments to the default tenant configured for the REALTIME table (DefaultTenant_REALTIME by default).
```

**Pull request closed without merging**
