### PR TITLE
fix flakyness by replacing HashSet and HashMap with LinkedHashSet and LinkedHashMap

### PR DESCRIPTION
**Pull request by Nemesis123925**
As Stated in the [issue/11939](https://github.com/apache/pinot/issues/11939)

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
We should not change `ProjectPlanNode` or `AggregationFunctionUtils` because it involves performance overhead to the production code. Can you try handling the order issue within the test?

**Review by walterddr — COMMENTED** [review]
+1 on @Jackie-Jiang 's comment. best solution is to use a parsed out explanation on project node and do a lexi-sorting on the test side on both the expected and actual value

**Comment by Nemesis123925** [comment]
Sure, let me try to do that

**Comment by Jackie-Jiang** [comment]
I can see a simpler way is to create a `HashSet` in the test and use `toString()` to generate the `PROJECT` clause since for the same java version the order should be deterministic

**Comment by Nemesis123925** [comment]
I try the way that Jackie Jiang proposed to use `toString()` of `HashSet` in the test to generate the `PROJECT` clause. It doesn't seems to work because the NonDex tool, which we use to check the falkyness, use differet and random seed for all the `HashSet`.  So almost in every run that the order is still not the same.

I check the way that walteraddr proposed, it seems like it needs to change the `validateRows` functions in `QueriesTestUtils.java` which is also used by other functions. Is there other better options that we can do this way?

**Comment by Nemesis123925** [comment]
I took a look at the failed test and don't have too much clue on how to solve that. Can I get a hint?

**Comment by Jackie-Jiang** [comment]
I guess we need to modify the test to not test on the string value. @walterddr any suggestion?

**Comment by Nemesis123925** [comment]
@walterddr Do you mean that I can create a different `validateRow` function for `ExplainPlanQueriesTest`, so we can solve the nondeternimism without changing the `HashSet` to `LinkedHashSet`?

**Comment by walterddr** [comment]
correct. explain query itself is not technically a "query" thus the response doesn't necessarily need to be interpretd/validated via the same method. 

see https://www.postgresql.org/docs/current/using-explain.html#USING-EXPLAIN:
> If you want to feed EXPLAIN's output to a program for further analysis, you should use one of its machine-readable output formats (XML, JSON, or YAML) instead.

we are not nearly there yet for checking the plan. but i think parsing each operator and compare in unordered fashion should be suffice now

**Comment by walterddr** [comment]
IMO at this stage adding a special handling for PROJECT operator, the rest can be string match should be fine.

**Comment by Nemesis123925** [comment]
Got it, let me try doing it. 
I also have a question such that If I created a function like `ValidateExplained`, do I need to write the test to test `ValidateExplained` function?

**Comment by Nemesis123925** [comment]
Also I am aware of the code coverage change of my change. Can I ask the tool we are using to detect code coverage here? so I can validate the coverage myself before updating the change

**Comment by walterddr** [comment]
- IMO you dont need to write test to validate test 
- i usually use intellij's Run with coverage to visualize inside the IDE, but you can also use mvn plugin to report such if that's more preferrable. there's no restriction here. 
 
Thank you for considering the test validity and coverage! this is superb!

**Comment by Nemesis123925** [comment]
I tried to change the `LinkedHashSet` and `LinkedHashMap` back to `HashSet` and `HashMap`, and found out that there is also nonderterminism in the `PLAN_START` node, which the `numSegmentsForThisPlan` also got randomized. While I am debuging this part, do you guys have any clue what is causing this nondeterminism?

**Comment by Nemesis123925** [comment]
I found that a part of the non-determinism of `numSegmentsForThisPlan` happens insde of [reduceOnDataTable](https://github.com/Nemesis123925/pinot/blob/master/pinot-core/src/test/java/org/apache/pinot/queries/ExplainPlanQueriesTest.java#L416), which in my understanding it compare and select the best query generated from the two servers, and add up the `numSegments` of them if the two queries are identical, which happens in [extractUniqueExplainPlansAcrossServers](https://github.com/Nemesis123925/pinot/blob/be74dc1429e4a72c2d51946167c281f039b60165/pinot-core/src/main/java/org/apache/pinot/core/query/reduce/ExplainPlanDataTableReducer.java#L131). Due to the non-determinism inside of the `PROJECT` clause created by `NonDex`, the test which suppose to have the two generates queries identical will differ from the `PROJECT` field, thus be understood as different queries by [extractUniqueExplainPlansAcrossServers](https://github.com/Nemesis123925/pinot/blob/be74dc1429e4a72c2d51946167c281f039b60165/pinot-core/src/main/java/org/apache/pinot/core/query/reduce/ExplainPlanDataTableReducer.java#L131). Thus the function will select the best one instead of adding their `numSegments` together, and create the nondeternism inside of the `numSegmentsForThisPlan` part.

For this part, I think the solution would be sorting the `PROJECT` clause before the two generated queries get into the  [extractUniqueExplainPlansAcrossServers](https://github.com/Nemesis123925/pinot/blob/be74dc1429e4a72c2d51946167c281f039b60165/pinot-core/src/main/java/org/apache/pinot/core/query/reduce/ExplainPlanDataTableReducer.java#L131) function, so the function will add the `numSegment` up instead of choising the better one.

However this is not the only cause of the non-deternism of the `numSegmentsForThisPlan` part. I found that applying `NonDex` will change the `numSegments` part even before the two generqte queries get into the [extractUniqueExplainPlansAcrossServers](https://github.com/Nemesis123925/pinot/blob/be74dc1429e4a72c2d51946167c281f039b60165/pinot-core/src/main/java/org/apache/pinot/core/query/reduce/ExplainPlanDataTableReducer.java#L131) function. So I will be keep exploring that part.

**Comment by walterddr** [comment]
i think we can separate the 2 issues, IIUC the project ordering issue is independent from the numSegmentsForThisPlan 
1. the ordering issue will occur even if only 1 server is servering, thus making sure the PROJECT node compare method in test is order invariant is the main thing.
2. the numSegmentsForThisPlan IMO is really a "judgement call", b/c 
    - technically speaking we should return ALL plans if there are multiple returns from different servers. 
    - however pinot doesn't really have a "logical" vs. "physical" plan concept, where "logical" is invariant of the data layout; and "physical" should be reported on every execution path. 
    - the result we are comparing here is neither truly logical or physical, that it only return a single plan ("as logical") but it consolidates from multiple server return ("physical"). 

hence my suggestion is we address the PROJECT ordering issue first in this PR and address the plan issue separately

CC @somandal who improved upon this part of the logic to chime in :-)

**Comment by Nemesis123925** [comment]
Roger that 

Here is the solution I suggest

In `QueriesTestUtils.java`, I write two new functions: 

```
public static void testExplainSegmentsResult(BrokerResponseNative brokerResponse, ResultTable expectedResultTable) {
    assertEquals(brokerResponse.getResultTable().getDataSchema(), expectedResultTable.getDataSchema());
    validateExplainedRows(brokerResponse.getResultTable().getRows(), expectedResultTable.getRows());
  }

private static void validateExplainedRows(List<Object[]> actual, List<Object[]> expected) {
    assertEquals(actual.size(), expected.size());
    for (int j = 0; j < actual.size(); j++) {
      Object[] act = actual.get(j);
      Object[] exp = expected.get(j);
      String attributeToSort = "PROJECT";
      assertEquals(act.length, exp.length);
      if (act[0].toString().startsWith(attributeToSort)) {
        char[] act0 = act[0].toString().toCharArray();
        char[] exp0 = exp[0].toString().toCharArray();
        Arrays.sort(act0);
        Arrays.sort(exp0);
        act[0] = new String(act0);
        exp[0] = new String(exp0);
      }
      assertEquals(act, exp);
    }
  }
```

In `ExplainPlanQueriesTest.java`, I redirect the `checkWithQueryExecutor` to call `testExplainSegmentsResult`

If apply this fix, instead of fixing all `27` flaky tests in `ExplainPlanQueriesTest.java`, this will fix `14` of them, which are
```
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelect
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectAggregate
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectAggregateUsingFilterGroupBy
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectAggregateUsingFilterGroupByVerbose
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectAggregateUsingFilterIndex
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectAggregateUsingFilterIndexGroupBy
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectAggregateUsingFilterIndexGroupByHaving
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectAggregateUsingFilterIndexGroupByOrderBy
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectAggregateUsingFilterOnTextIndexColumn
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectColumnUsingFilterOnRangeIndexColumn
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectColumnsUsingFilter
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectColumnsUsingFilterOnInvertedIndexColumn
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectColumnsVariationsOfAndOperators
org.apache.pinot.queries.ExplainPlanQueriesTest#testSelectColumnsVariationsOfOrOperators
```
If you guys think this fix is good, I will push the new commit.

**Review by walterddr — APPROVED** [review]

**Pull request merged**
