### PR TITLE
fix FST Like query benchmark to remove SQL parsing from the measurement

### PR DESCRIPTION
**Pull request by richardstartin**
I noticed that the FST Like benchmark results vary a lot:

```
Benchmark                                                 Mode  Cnt  Score   Error  Units
BenchmarkNativeAndLuceneBasedLike.testLuceneBasedFSTLike  avgt   25  3.127 ± 0.578   s/op
BenchmarkNativeAndLuceneBasedLike.testNativeBasedFSTLike  avgt   25  3.440 ± 0.555   s/op
```

When running these benchmarks with `-prof jfr` to figure out what they were actually measuring I noticed a couple of things:

1. Most of the time is spent parsing SQL creating the query context
Screenshot 2022-01-31 at 17 54 48
2. Because the benchmark doesn't properly segregate the FST types or clean up after itself properly (it uses a testng `AfterClass` annotation which JMH doesn't know anything about), the `testNativeBasedFSTLike` sometimes measures the Lucene implementation, but when it does measure the Native implementation, the SQL parsing frames are much narrower relative to the construction of the filter operator.

Screenshot 2022-01-31 at 17 58 54

After a couple of changes to use proper JMH lifecycle and to factor out SQL parsing into the setup, most of the benchmark time is spent in construction of the filter operator:

Lucene:
Screenshot 2022-01-31 at 17 48 12
Native:
Screenshot 2022-01-31 at 17 48 48

The results are more stable and tell a different story, which should help drive future improvement in this space:

```
Benchmark                                (_fstType)  (_intBaseValue)  (_numRows)                                                                 (_query)  Mode  Cnt    Score    Error  Units
BenchmarkNativeAndLuceneBasedLike.query      LUCENE             1000     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt   25   65.626 ±  1.454  us/op
BenchmarkNativeAndLuceneBasedLike.query      NATIVE             1000     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt   25  232.908 ± 17.302  us/op
```

### CODE REVIEW

**Comment by richardstartin** [comment]
I've added a parameter to vary the number of blocks iterated over so this benchmark doesn't just measure planning.

**Comment by richardstartin** [comment]
At 100 blocks planning time still dominates this benchmark, but the cost of block iteration can be seen to increase for Lucene:

Lucene:
Screenshot 2022-01-31 at 18 43 11

Native:
Screenshot 2022-01-31 at 18 42 30
 

```
Benchmark                                (_fstType)  (_intBaseValue)  (_numBlocks)  (_numRows)                                                                 (_query)  Mode  Cnt    Score    Error  Units
BenchmarkNativeAndLuceneBasedLike.query      LUCENE             1000             0     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5   58.150 ±  8.321  us/op
BenchmarkNativeAndLuceneBasedLike.query      LUCENE             1000             1     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5   64.661 ±  6.074  us/op
BenchmarkNativeAndLuceneBasedLike.query      LUCENE             1000            10     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5   70.470 ±  3.328  us/op
BenchmarkNativeAndLuceneBasedLike.query      LUCENE             1000           100     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5  135.908 ±  6.255  us/op
BenchmarkNativeAndLuceneBasedLike.query      NATIVE             1000             0     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5  223.925 ± 28.949  us/op
BenchmarkNativeAndLuceneBasedLike.query      NATIVE             1000             1     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5  243.418 ± 78.130  us/op
BenchmarkNativeAndLuceneBasedLike.query      NATIVE             1000            10     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5  232.884 ± 18.010  us/op
BenchmarkNativeAndLuceneBasedLike.query      NATIVE             1000           100     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5  299.587 ± 30.918  us/op
```

**Comment by Jackie-Jiang** [comment]
@atris Can you please take a look at this PR, and see if the benchmark result is valid? If so, we should revisit the native FST solution and make its performance at least on par with Lucene FST

**Comment by atris** [comment]
Thanks for the tag, I will take a look tomorrow

**Comment by richardstartin** [comment]
Added a query to match a prefix - Lucene winning for prefix queries too:

```
Benchmark                                (_fstType)  (_intBaseValue)  (_numBlocks)  (_numRows)                                                                    (_query)  Mode  Cnt    Score    Error  Units
BenchmarkNativeAndLuceneBasedLike.query      LUCENE             1000           100     2500000     SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5  140.027 ± 18.472  us/op
BenchmarkNativeAndLuceneBasedLike.query      LUCENE             1000           100     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE 'www.domain%'  avgt    5  177.205 ± 15.342  us/op
BenchmarkNativeAndLuceneBasedLike.query      NATIVE             1000           100     2500000     SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE '%domain%'  avgt    5  304.332 ± 92.048  us/op
BenchmarkNativeAndLuceneBasedLike.query      NATIVE             1000           100     2500000  SELECT INT_COL, URL_COL FROM MyTable WHERE DOMAIN_NAMES LIKE 'www.domain%'  avgt    5  290.019 ± 57.574  us/op
```

**Review by siddharthteotia — APPROVED** [review]

**Comment by Jackie-Jiang** [comment]
@atris Have you got a chance to look at this PR?

**Comment by richardstartin** [comment]
I'm going to go ahead and merge this.

**Comment by atris** [comment]
> I'm going to go ahead and merge this.

Thanks for this, @richardstartin . I have been swamped at work so couldn't take a look. I will investigate and update on your findings.

**Pull request merged**
