### PR TITLE
[pinot-spark-connector] Add option to connect using GRPC

### PR DESCRIPTION
**Pull request by cbalci**
Adding a configuration option to the Pinot Spark Connector to use GRPC endpoint when reading data from Pinot.
As already documented, GRPC is more efficient when reading large amounts of data, and this use case arises often when using Pinot Spark Connector.

The option is added as:
```
  .option("useGrpcServer", "true")
```

- The option is disabled by default, so no backwards incompatibility issues expected
- Documentation will be updated separately after some wider testing

### CODE REVIEW

**Comment by cbalci** [comment]
@yupeng9 ptal

**Comment by xiangfu0** [comment]
Pinot stores grpc port in helix instance config, you can fetch it from controller API  `/instances/<instance_id>`. So no need to configure it manually

Some code ref from prestodb: 
https://github.com/prestodb/presto/blob/master/presto-pinot-toolkit/src/main/java/com/facebook/presto/pinot/PinotClusterInfoFetcher.java#L600
and 
https://github.com/prestodb/presto/blob/master/presto-pinot-toolkit/src/main/java/com/facebook/presto/pinot/PinotClusterInfoFetcher.java#L588

**Comment by cbalci** [comment]
Thanks for the pointers @xiangfu0! I updated the changes to fetch grpc port information from the controller in a similar way implemented in Presto. Please take another look.

**Comment by cbalci** [comment]
@xiangfu0, while I'm on it, I also updated the connector to use Pinot Controller API for reading host information, rather than parsing instance name.
Please take another look and let me know what you think.

**Review by xiangfu0 — APPROVED** [review]
lgtm

**Pull request merged**
