### PR TITLE
Added /uptime and /start-time for all components. Addressed comments and fixed tests from pull request 12389. 

### PR DESCRIPTION
**Pull request by suyashpatel98**
Addresses #12298. Added /uptime and /start-time for all components. Addressed comments and verified tests pass from pull request [12389](https://github.com/apache/pinot/pull/12389) (Closed that request because the history of that PR got messy). Tested /uptime and /start-time endpoints on my local machine. See the attached images

uptime
start-time

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
Do we want uptime in seconds, or in a more human readable format?

**Comment by suyashpatel98** [comment]
> Do we want uptime in seconds, or in a more human readable format?

@Jackie-Jiang Xiang in the old PR [here](https://github.com/apache/pinot/pull/12389) was inclined towards returning just a number. I am okay either way

**Comment by suyashpatel98** [comment]
ForwardIndexHandlerTest.testAddOtherIndexForForwardIndexDisabledColumn() is a flaky test. There is an existing open issue - #11928

**Comment by xiangfu0** [comment]
> as inclined towards returning just a number. I am okay either way - don't have a strong preference

I prefer epoch value, UI side can decide how to show it.

**Review by xiangfu0 — APPROVED** [review]

**Comment by xiangfu0** [comment]
Thanks for adding this feature @suyashpatel98 !

**Pull request merged**
