### PR TITLE
Allow schema to be created with JSON config in UI

### PR DESCRIPTION
**Pull request by jayeshchoudhary**
this is `ui`, `feature`

Closes - https://github.com/apache/pinot/issues/11789

## Description
- Add UI to add Schema directly using JSON
- This is helpful when user has the entire JSON handy
- UI still keeps Form Way to add Schema along with JSON view

## Screenshot
https://github.com/apache/pinot/assets/41536903/d92842ec-7c8d-4c32-8f59-3ad4390bf698

### CODE REVIEW

**Comment by jayeshchoudhary** [comment]
Please review - @ksnijjer @Jackie-Jiang

**Comment by xiangfu0** [comment]
This is fantastic! 
Thanks @jayeshchoudhary !

**Review by xiangfu0 — APPROVED** [review]

**Review by walterddr — COMMENTED** [review]
looks good to me. 
do you have a demo that edit/paste a valid JSON and switch back to original view (does it shows the line items parsed properly?

**Comment by jayeshchoudhary** [comment]
> looks good to me. do you have a demo that edit/paste a valid JSON and switch back to original view (does it shows the line items parsed properly?

No, we reset the config when the view gets changed
This is because to parse values back and forth we need to check many conditions/validations, plus working with forms make it even more complex.

**Comment by xiangfu0** [comment]
> looks good to me. do you have a demo that edit/paste a valid JSON and switch back to original view (does it shows the line items parsed properly?

I think we can add this later.

**Comment by walterddr** [comment]
i dont really think we need to add later. simply have a banner warning when switching view "you have unsaved schema edit, do you want to proceed" is intuitive enough. and frankly i dont think any user will mix the view usages 

i asked the question simply want to make sure ppl arent allow to do exactly that

**Pull request merged**
