### PR TITLE
Fixing the vulnerabilities of amazon corretto pinot-base-runtime docker image.

### PR DESCRIPTION
**Pull request by abhioncbr**
As per https://github.com/apache/pinot/issues/13461, This PR tries to fix the vulnerabilities of the Amazon corretto jdk image. Here are some details
- There are 0 vulnerabilities in the Amazon corretto [11-al2023-jdk⁠](https://github.com/corretto/corretto-docker/blob/cdcc44b8859544a47ce8c64ed0b3cc051a8c58c8/11/jdk/al2023/Dockerfile) image, however while installing git and several other packages we get around 50 high vulnerability. The base image is Amazon Linux-based, and all the packages are installed from the Amazon repo list. Using the fedora epel repo is cumbersome; hence, in this PR, we are switching to an Alpine Linux-based image.
- Using a based image, reduced the size of the image; it is now close to 400MB only.
- With this change, there is only now 1 Medium vulnerability because of curl package

```bash
docker scout quickview 
Abhi-Sharma's-MacBook-Pro :: ~/work/pinot ‹13461-fix-amazoncorretto-vuln*› » docker scout quickview                                                                                 (sbx/consumer)
    i New version 1.13.0 available (installed version is 1.11.0) at https://github.com/docker/scout-cli
    ✓ Image stored for indexing
    ✓ Indexed 70 packages

    i Base image was auto-detected. To get more accurate results, build images with max-mode provenance attestations.
      Review docs.docker.com ↗ for more information.
      
  Target             │  local://apachepinot/pinot-base-runtime:11-amazoncorretto  │    0C     0H     1M     0L   
    digest           │  d52984cecc31                                              │                              
  Base image         │  amazoncorretto:11-alpine                                  │    0C     0H     0M     0L   
  Updated base image │  amazoncorretto:22-alpine                                  │    0C     0H     0M     0L   
                     │                                                            │                              


```

Also, I would like to highlight the [PR comment](https://github.com/apache/pinot/pull/10422/files#r1136640737) by @gortiz, I think we should follow the route suggested in the comment and also recommend two sets of Pinot images, one with [distroless image ](https://github.com/GoogleContainerTools/distroless) and other set with various packages installed.

### CODE REVIEW

**Comment by gortiz** [comment]
Personally, I don't like Alpine images given the docker image size is not that important* and the fact that Alpine uses musl instead of glib may have unexpected side effects. But I understand others may think differently.

What I don't get is why we need to remove the Amazon Corretto support. Right now we publish three different flavors (corretto, microsoft and openjdk). We can just create a new one. In case we need to remove one, probably openjdk should be the one to delete (given openjdk docker image is not recommended for production.


\* In case we really want to improve that we should focus on other parts of the image including more efficient docker cache usage.

**Comment by abhioncbr** [comment]
> 
> What I don't get is why we need to remove the Amazon Corretto support. Right now we publish three different flavors (corretto, microsoft and openjdk). We can just create a new one. In case we need to remove one, probably openjdk should be the one to delete (given openjdk docker image is not recommended for production.
> 
Minor correction here: the image is still Amazon corretto, jdk. It's just that the OS is now Alpine instead of Amazon Linux. Yes, I agree we need to delete openjdk, given that it's not recommended for production.

**Comment by gortiz** [comment]
Could you then modify this PR to substitute openjdk with your alpine solution?

**Comment by gortiz** [comment]
I'm ok with stopping publishing openjdk. But as said above, I prefer to use images not based on Alpine, which doesn't use glibc. I strongly believe using alpine is a bad habit people has because they just focus on the reported docker image size instead of actually understanding how docker layers work.

**Comment by gortiz** [comment]
I've just found [this blogpost](https://martinheinz.dev/blog/92) which is not super updated, but it is good to show the impact using Alpine has in the past. TBH I don't think it is worth to fall into something like that just to reduce some MBs. It should be other and better options to reduce the vulns in our images.

**Comment by abhioncbr** [comment]
Amazon Corretto JDK docker images are only available on Amazon Linux and Alpine flavour. They do have the Debian based docker files in the repo, however they don't publish it. Here is the [reference](https://github.com/corretto/corretto-docker/blob/043a4edae59728f75df4c89a4df2dea770763109/README.md)

If we want to use Amazon Corretto, we can build these Debian-based Corretto images and publish them on the Apache Pinot Docker hub for further build processes. WDYT @gortiz / @xiangfu0 ?

**Comment by gortiz** [comment]
`trivy image apachepinot/pinot:latest-21-amazoncorretto` only shows 2 high/critical vulns and both of them are in Java. Therefore I think the current corretto image is good enough and I won't change it.

**Comment by abhioncbr** [comment]
> `trivy image apachepinot/pinot:latest-21-amazoncorretto` only shows 2 high/critical vulns and both of them are in Java. Therefore I think the current corretto image is good enough and I won't change it.

sure, closing the PR. thanks

**Comment by gortiz** [comment]
> Therefore I think the current corretto image is good enough and I won't change it.

I guess wording wasn't great. I wanted to say that I don't think we need to opt out from corretto. As said before, having an alpine image is fine as long as it is not the default image.

**Pull request closed without merging**
