### PR TITLE
Upgrading Apache Helix to latest version

### PR DESCRIPTION
**Pull request by soumitra-st**
Upgrading Apache Helix to latest version to recent fixes and enhancements

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
@jackjlli Do you know if it is safe to upgrade to the latest Helix version 1.3.0?

**Comment by jackjlli** [comment]
I'm syncing up with Helix team on this PR and will get back to you. Before that please hold off merging this PR.

**Review by jackjlli — APPROVED** [review]
Validated that this Helix version is backward compatible with the existing version and it works as expected. We should be good to merge this PR.

**Comment by Jackie-Jiang** [comment]
Find a [bug](https://github.com/apache/helix/issues/2613) in helix, and I feel it might be a critical one. We might need to revert it back to `1.0.4`. The bug was introduced in `1.1.0`

**Comment by jackjlli** [comment]
Thanks @Jackie-Jiang for identifying the issue! I've synced up with Helix team about the bug. I'm good with reverting the version bump for now.

**Pull request merged**
