### PR TITLE
Upgrade Calcite to 1.36.0

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Upgrade Calcite from `1.30.0` -> `1.36.0`.

There are some behavior changes, thus changing the code to adapt:
- Moved `CoreRules.AGGREGATE_CASE_TO_FILTER` after `CoreRules.AGGREGATE_REDUCE_FUNCTIONS` because it is changed to be applied on `SUM0` instead of `SUM`
- Copied and modified the `Parser.jj` template because Pinot doesn't follow standard `DATE_TRUNC` syntax
- (bugfix) Remove unused fields after decorrelate query

New support:
- Standard `DATE_TRUNC`: `DATE_TRUNC(DAY, millisSinceEpoch)`, notice there is no single quotes around `DAY`
- Array construct with string literal: `ARRAY'{1,2,3}'`

### CODE REVIEW

**Comment by xiangfu0** [comment]
wow！

**Review by xiangfu0 — APPROVED** [review]

**Comment by gortiz** [comment]
Are we sure we needed to copy the whole jj file? AFAIU Calcite parser is designed to be extensible.

**Comment by Jackie-Jiang** [comment]
> Are we sure we needed to copy the whole jj file? I'm not an expert here, but AFAIU Calcite parser is designed to be extensible.

I tried multiple approaches and didn't find a way to modify function defined in `Parser.jj`. The closest try is to add a new signature as `builtinFunctionCallMethods`, but that is too late as it is injected after `DateTruncFunctionCall()`. Not sure if it is a Calcite bug because IMO the `builtinFunctionCallMethods` should be injected before parsing it with the default implementations

**Comment by robertzych** [comment]
> Not sure if it is a Calcite bug because IMO the builtinFunctionCallMethods should be injected before parsing it with the default implementations

Should we open a Calcite issue for this?

**Comment by Jackie-Jiang** [comment]
@robertzych Sure, we can file an issue and confirm what I did is necessary.

The long term plan could be we maintain our own parser just for Pinot. Currently Calcite parser tries to adapt to all SQL dialects from different DBs, which can be confusing.
Taking `DATE_TRUNC` as an example (the one I have to modify):
- The standard one: `DATE_TRUNC(YEAR, timestamp)`
- BigQuery: `DATE_TRUNC(d, YEAR)`
- Redshift: `DATE_TRUNC('year', DATE '2008-09-08')`
- Postgres: `DATE_TRUNC(text, timestamp with time zone, text)` (not supported)
- Pinot: Similar to Postgres but with 2-5 arguments

**Comment by robertzych** [comment]
I just filed the Calcite issue: https://issues.apache.org/jira/browse/CALCITE-6381

**Pull request merged**
