### PR TITLE
upgrade helix to 1.0.2

### PR DESCRIPTION
**Pull request by richardstartin**
## Description

In Apache Helix 0.9.8, a very expensive Jackson `ObjectMapper` is constructed for each and every serialized `ZNRecord` in `ZNRecordSerializer`:

```java
  @Override
  public byte[] serialize(Object data) {
   ...
    // do serialization
    ObjectMapper mapper = new ObjectMapper();
    SerializationConfig serializationConfig = mapper.getSerializationConfig();
    serializationConfig.set(SerializationConfig.Feature.INDENT_OUTPUT, true);
    serializationConfig.set(SerializationConfig.Feature.AUTO_DETECT_FIELDS, true);
    serializationConfig.set(SerializationConfig.Feature.CAN_OVERRIDE_ACCESS_MODIFIERS, true);
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    byte[] serializedBytes;
    boolean isCompressed = false;

    try {
      mapper.writeValue(baos, data);
      serializedBytes = baos.toByteArray();
      ...
```

This was fixed last year: https://github.com/apache/helix/pull/1293/files#diff-3eaf04c3cf3dc03110404530dd4d18d7b9dbb8afeefebe4b4f57e73e043fe274R42

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by richardstartin** [comment]
Some packages were moved around in 1.0.0 and this ended up being quite a large change.

**Comment by richardstartin** [comment]
There seem to be nontrivial behaviour changes in Helix 1.0 which make this more challenging than expected.

**Comment by mcvsubbu** [comment]
@richardstartin we are planning to upgrade to helix 1.0. We are working closely with the the helix team in this regard. Helix 1.0 has been out for a while now, and is considered to be stable at this point. However, it is a source incompatible change. So, we need to move carefully.  We will raise an issue for it soon, and work on that.

We will probably do that in a branch, and merge to master when everything looks good in Linkedin production environment.

Meanwhile, can you please describe the behavior change you found?

**Comment by mcvsubbu** [comment]
Copy pasting message from @richardstartin  before it disappears from chat

hi Subbu, the upgrade wasn't simple and it's possible I made some mistakes doing it, but several controller tests time out on my branch. E.g. in ControllerInstanceToggleTest the cluster doesn't get set up properly.
09:26:27.461 [ZkClient-EventThread-33-localhost:2191] ERROR org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks - Interrupted waiting for success
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[?:?]
	at java.lang.Object.wait(Object.java:328) ~[?:?]
	at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:249) [helix-core-1.0.2.jar:1.0.2]
	at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1306) [helix-core-1.0.2.jar:1.0.2]
	at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:85) [helix-core-1.0.2.jar:1.0.2]
	at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1332) [helix-core-1.0.2.jar:1.0.2]
	at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99) [helix-core-1.0.2.jar:1.0.2]
09:26:30.819 [HelixController-pipeline-default-ControllerTestUtils-(ed00bafa_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:30.828 [HelixController-pipeline-default-ControllerTestUtils-(6ca9c1f1_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:30.834 [HelixController-pipeline-default-ControllerTestUtils-(a5f87de1_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:30.841 [HelixController-pipeline-default-ControllerTestUtils-(3801afe7_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:30.852 [HelixController-pipeline-default-ControllerTestUtils-(3805570d_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:31.251 [HelixController-pipeline-default-ControllerTestUtils-(aaec8ce8_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:31.277 [HelixController-pipeline-default-ControllerTestUtils-(d8cc3e98_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:31.289 [HelixController-pipeline-default-ControllerTestUtils-(1b94a4b9_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:31.297 [HelixController-pipeline-default-ControllerTestUtils-(842b241b_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:31.307 [HelixController-pipeline-default-ControllerTestUtils-(0b4b5414_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:31.314 [HelixController-pipeline-default-ControllerTestUtils-(8bedd9f7_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
09:26:31.320 [HelixController-pipeline-default-ControllerTestUtils-(6477b0f8_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []
Oct 01, 2021 9:26:37 AM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:18998]
Oct 01, 2021 9:26:37 AM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
09:26:41.821 [ZkClient-EventThread-320-localhost:2191] ERROR org.apache.helix.messaging.handling.HelixTaskExecutor - Message 1375bc51-25a5-4e8e-a291-e407ecb959c2 cannot be processed: 1375bc51-25a5-4e8e-a291-e407ecb959c2, {CREATE_TIMESTAMP=1633076801818, ClusterEventName=InstanceConfigChange, FROM_STATE=ONLINE, MSG_ID=1375bc51-25a5-4e8e-a291-e407ecb959c2, MSG_STATE=new, MSG_TYPE=STATE_TRANSITION, PARTITION_NAME=toggleTable72090524845971, RESOURCE_NAME=toggleTable_OFFLINE, RESOURCE_TAG=toggleTable_OFFLINE, RETRY_COUNT=3, SRC_NAME=localhost_18998, SRC_SESSION_ID=100044bca960003, STATE_MODEL_DEF=SegmentOnlineOfflineStateModel, STATE_MODEL_FACTORY_NAME=DEFAULT, TGT_NAME=Server_localhost_3, TGT_SESSION_ID=100044bca960018, TO_STATE=OFFLINE}{}{}Partition toggleTable72090524845971 current state is same as toState (ONLINE->OFFLINE) from message.
09:26:41.822 [ZkClient-EventThread-320-localhost:2191] ERROR org.apache.helix.util.StatusUpdateUtil - StatusUpdate Error record: 100044bca960018__toggleTable_OFFLINE, {}{HELIX_ERROR     20211001-092641.000821 STATE_TRANSITION f04e6b17-edab-495a-bf33-ce056dec5c3a={AdditionalInfo=Partition toggleTable72090524845971 current state is same as toState (ONLINE->OFFLINE) from message., Class=class org.apache.helix.participant.HelixStateMachineEngine, MSG_ID=1375bc51-25a5-4e8e-a291-e407ecb959c2, Message state=NEW}}{}
My only motivation to upgrade was to avoid creating an ObjectMapper on each ZN serialization and it was taking more time than justified. So if you plan to do it at LinkedIn with the Helix team I think it's better that way.

**Comment by monicaluodialpad** [comment]
Hey I am getting the same issue above. Any solution?
> [HelixController-pipeline-default-ControllerTestUtils-(6477b0f8_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer - No instances or active instances available for resource leadControllerResource, allInstances: [], liveInstances: [], activeInstances: []

**Comment by Jackie-Jiang** [comment]
@monicaluodialpad Which Helix version are you running?

**Pull request closed without merging**
