### PR TITLE
Add Wait Time to Fix Local `SparkSegmentMetadataPushIntegrationTest`

### PR DESCRIPTION
**Pull request by ashishjayamohan**
- Adds sleep time to `SparkSegmentMetadataPushIntegrationTest.java` to allow integration tests to run locally (previously, had error with Helix state transition due to premature call to `buildSegmentFromAvro()`)

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
Any idea why we need to add a sleep? Everything seems happen locally in a synchronous fashion

**Comment by ashishjayamohan** [comment]
@Jackie-Jiang This PR addresses the issue with local tests that I ran into [here](https://github.com/apache/pinot/pull/14199). Instead of being an issue with the test priorities as I assumed before, I've identified the issue as likely being a premature call to `buildSegmentFromAvro()` before everything has time to set up for these specific tests. When I don't have this sleep, the test runs into an issue with the `HelixStateTransitionHandler`. I noticed that this issue was averted when I ran it in debug mode and had a slight delay before building the segment from the avro file.

**Comment by Jackie-Jiang** [comment]
Can you share the stack trace or error log of the failure? `buildSegmentFromAvro()` is not touching helix, so that shouldn't be the root cause

**Comment by ashishjayamohan** [comment]
Definitely, here's what I'm seeing when running the tests locally (specifically after running `testSparkSegmentMetadataPushWithoutConsistentPushWithBatchSegmentUpload`:
```
16:19:48.871 WARN [BrokerRoutingManager] [HelixTaskExecutor-message_handle_thread_108] Cannot enable SegmentPartitionMetadataManager. Expecting SegmentPartitionConfig with exact 1 partition column
16:19:49.679 ERROR [HelixStateTransitionHandler] [HelixTaskExecutor-message_handle_thread_94] Exception while executing a state transition task mytable_16071_16101__no_consistent_push
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor220.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:350) ~[helix-core-1.3.1.jar:1.3.1]
	at org.apache.helix.messaging.handling.HelixStateTransitionHandler.handleMessage(HelixStateTransitionHandler.java:278) [helix-core-1.3.1.jar:1.3.1]
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:97) [helix-core-1.3.1.jar:1.3.1]
	at org.apache.helix.messaging.handling.HelixTask.call(HelixTask.java:49) [helix-core-1.3.1.jar:1.3.1]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: Table data manager is already shut down, cannot add ONLINE segment: mytable_16071_16101__no_consistent_push to table: mytable_OFFLINE
	at com.google.common.base.Preconditions.checkState(Preconditions.java:836) ~[guava-33.3.1-jre.jar:?]
	at org.apache.pinot.core.data.manager.BaseTableDataManager.addOnlineSegment(BaseTableDataManager.java:307) ~[classes/:?]
	at org.apache.pinot.server.starter.helix.HelixInstanceDataManager.addOnlineSegment(HelixInstanceDataManager.java:275) ~[classes/:?]
	at org.apache.pinot.server.starter.helix.SegmentOnlineOfflineStateModelFactory$SegmentOnlineOfflineStateModel.onBecomeOnlineFromOffline(SegmentOnlineOfflineStateModelFactory.java:131) ~[classes/:?]
	... 11 more
16:19:49.682 ERROR [StateModel] [HelixTaskExecutor-message_handle_thread_94] Default rollback method invoked on error. Error Code: ERROR
16:19:49.683 ERROR [HelixTask] [HelixTaskExecutor-message_handle_thread_94] Message execution failed. msgId: b877dec8-d56c-47b9-abcb-ba5182efc614, errorMsg: java.lang.reflect.InvocationTargetException
16:19:49.683 ERROR [HelixStateTransitionHandler] [HelixTaskExecutor-message_handle_thread_94] Skip internal error. errCode: ERROR, errMsg: null
16:19:49.687 WARN [BaseInstanceSelector] [ClusterChangeHandlingThread] Failed to find servers hosting old segment: mytable_16071_16101__no_consistent_push for table: mytable_OFFLINE (all candidate instances: [] are disabled, counting segment as unavailable)
16:19:49.689 ERROR [MessageGenerationPhase] [HelixController-pipeline-default-SparkSegmentMetadataPushIntegrationTest-(12309698_DEFAULT)] Event 12309698_DEFAULT : Unable to find a next state for resource: mytable_OFFLINE partition: mytable_16071_16101__no_consistent_push from stateModelDefinitionclass org.apache.helix.model.StateModelDefinition from:ERROR to:ONLINE
16:19:49.693 ERROR [MessageGenerationPhase] [HelixController-pipeline-default-SparkSegmentMetadataPushIntegrationTest-(f6fb9506_DEFAULT)] Event f6fb9506_DEFAULT : Unable to find a next state for resource: mytable_OFFLINE partition: mytable_16071_16101__no_consistent_push from stateModelDefinitionclass org.apache.helix.model.StateModelDefinition from:ERROR to:ONLINE
16:19:49.697 ERROR [MessageGenerationPhase] [HelixController-pipeline-default-SparkSegmentMetadataPushIntegrationTest-(15f504b0_DEFAULT)] Event 15f504b0_DEFAULT : Unable to find a next state for resource: mytable_OFFLINE partition: mytable_16071_16101__no_consistent_push from stateModelDefinitionclass org.apache.helix.model.StateModelDefinition from:ERROR to:ONLINE
```

**Comment by Jackie-Jiang** [comment]
I'm not able to reproduce this locally. Can you try if #14334 can fix this issue?

**Comment by ashishjayamohan** [comment]
Yep, that PR fixes the issue. I'm going to go ahead and close this PR then.

**Pull request closed without merging**
