### PR TITLE
Pass context in operators instead of individual objects

### PR DESCRIPTION
**Pull request by KKcorps**
This will allow us to easily add more params to operators constructors in the future without major refactoring.

### CODE REVIEW

**Comment by KKcorps** [comment]
After discussion with @walterddr it seems like not the right approach to go with. Reason being the `PlanRequestContext` object is destroyed after the visitor is called. Any operator if it caches this object, will not be able to use it at runtime. Better to not take this risk in the future.

**Comment by gortiz** [comment]
So we should close this PR?

**Review by walterddr — COMMENTED** [review]
yes this one can be closed in favor of #10299 ?

**Comment by gortiz** [comment]
But #10299 isn't focused on passing context operators, right? I think we still need to think how to pass this contextual information in Pinot. I've found several places where contextual information is needed and in order to do not add tons of arguments to the constructor I had to delegate on static methods. For example when dealing with #10183 or sending metrics. I have the feeling that we should start thinking on using some dependency injector in order to try to decouple our objects from the contextual arguments

**Comment by KKcorps** [comment]
I agree with @gortiz here. Passing more than 3-4 arguments is simply not the correct way and also increases the time to make small changes to functions.

**Pull request closed without merging**
