### PR TITLE
11085: Added commons-configuration2 dependency.

### PR DESCRIPTION
**Pull request by abhioncbr**
As per the [issue](https://github.com/apache/pinot/issues/11085).
- This is related to the first task i.e. adding the `commons-configuration2` dependency in the root pom file. 
- Also added an exclusion for the `commons-configuration2` jar import through hadoop-common dependency. 

cc @Jackie-Jiang

### CODE REVIEW

**Comment by abhioncbr** [comment]
@Jackie-Jiang, can you please retrigger the failing tests, as failure is irrelevant to this change? And also, can you please review it?

Thanks

**Comment by xiangfu0** [comment]
I saw an extra file added : `pinot-plugins/pinot-batch-ingestion/pinot-batch-ingestion-hadoop/pinot-plugins.tar.gz`, is it required?

**Comment by abhioncbr** [comment]
> I saw an extra file added : `pinot-plugins/pinot-batch-ingestion/pinot-batch-ingestion-hadoop/pinot-plugins.tar.gz`, is it required? image

It's not required. Let me delete the unwanted file.

**Review by walterddr — COMMENTED** [review]
retriggering since all failure are on jdk-11. let's see the results. otherwise looks good to me.

**Comment by abhioncbr** [comment]
> > I saw an extra file added : `pinot-plugins/pinot-batch-ingestion/pinot-batch-ingestion-hadoop/pinot-plugins.tar.gz`, is it required? image
> 
> It's not required. Let me delete the unwanted file.

Actually, this unwanted file was added last week in this [PR](https://github.com/apache/pinot/pull/11591); I am deleting it. Thanks

**Review by walterddr — APPROVED** [review]
lgtm.  @xiangfu0 @abhioncbr i missed the doc discussion please kindly take another look before we merge it.

**Review by xiangfu0 — APPROVED** [review]

**Pull request merged**
