### PR TITLE
Support Environment variable values in ingestion spec

### LINKED ISSUE #6115: Support environment variables injection for Pinot ingestion job
Pinot supports launch ingestion jobs with a template file and a command line option to set the values.

This logic is handled in class: `org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher`.

Here we want to also support environment variables to set those values.

This will be convenient for users in k8s environment with dynamic configs settings.

E.g. user can do dynamic job loading with k8s cronjob by setting:

- Set `inputDirURI` to `'s3://event-logs/dt=${JOB_DATE}/'` in `batch_job_spec.yaml` file.
- Set container  `env` with `JOB_DATE` to `$(date -u +"%Y-%m-%d")`, so `JOB_DATE` will be the runtime date.
- Set container `args` to
```
[
    "LaunchDataIngestionJob",
    "-jobSpecFile",
    "/home/pinot/pinot-config/batch_job_spec.yaml"
]
```

### PR DESCRIPTION
**Pull request by ravishankar15**
Fix #6115

The order of substitution would be,
1. PropertyFile
2. Environment values
3. Command line arguments

### CODE REVIEW

**Comment by kishoreg** [comment]
This is amazing! Thanks for the contribution.

**Review by Jackie-Jiang — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by Jackie-Jiang** [comment]
@ravishankar15 Could you please also help revise the pinot documentation for this part: https://docs.pinot.apache.org/configuration-reference/job-specification
The source code for the documentation can be found here: https://github.com/pinot-contrib/pinot-docs

**Comment by ravishankar15** [comment]
> @ravishankar15 Could you please also help revise the pinot documentation for this part: https://docs.pinot.apache.org/configuration-reference/job-specification The source code for the documentation can be found here: https://github.com/pinot-contrib/pinot-docs

Yeah sure, Documentation PR: https://github.com/pinot-contrib/pinot-docs/pull/106

**Pull request merged**
