### PR TITLE
UI: fix sql exception display

### PR DESCRIPTION
**Pull request by jayeshchoudhary**
## What does this PR do?
- Fixes SQL exception message formatting (earlier it used to ignore escape sequence which made the exception hard to read, but now the message is formatted properly)
- Fix message overflow from the box issue

## Screenshots 

Before 
image

After
image

### CODE REVIEW

**Comment by jayeshchoudhary** [comment]
@xiangfu0 @mayankshriv

**Comment by gortiz** [comment]
I think we would also need the error code to be printed. Although the stack trace is quite useful, the error code is more useful to classify the error.

**Comment by jayeshchoudhary** [comment]
> I think we would also need the error code to be printed. Although the stack trace is quite useful, the error code is more useful to classify the error.

@gortiz The error code I saw was not correct, e.g. In the above screenshot, we got 200 as errorCode. I thought it is not very helpful hence removed it, I can add that back if required.

**Comment by xiangfu0** [comment]
> > I think we would also need the error code to be printed. Although the stack trace is quite useful, the error code is more useful to classify the error.
> 
> @gortiz The error code I saw was not correct, e.g. In the above screenshot, we got 200 as errorCode. I thought it is not very helpful hence removed it, I can add that back if required.

Please add it back once you got time, thanks!

**Pull request merged**
