### PR TITLE
Make RequestUtils always return a string array when getTableNames

### PR DESCRIPTION
**Pull request by xiangfu0**
Make RequestUtils always return a string array when getTableNames

### CODE REVIEW

**Comment by xiangfu0** [comment]
@abhioncbr ^^

**Review by walterddr — APPROVED** [review]
lgtm. great catch on the v1 compileToJoin issue

**Comment by abhioncbr** [comment]
Overall, it looks good to me. Thanks.
I initially followed the same approach to fix the issue but later realized that we have another [task](https://github.com/apache/pinot/issues/11003) for the same work and was looking can we cover the issue along with the redesign work.

**Comment by xiangfu0** [comment]
> Overall, it looks good to me. Thanks. I initially followed the same approach to fix the issue but later realized that we have another [task](https://github.com/apache/pinot/issues/11003) for the same work and was looking can we cover the issue along with the redesign work.

I think client side should also get all the tables then check if they are on the same tenants, then decide how to pick the broker tenant for query execution.

**Pull request merged**
