### PR TITLE
Remove presto jdk8 related dependencies

### PR DESCRIPTION
**Pull request by xiangfu0**
- Remove jdk8 libs
- Remove presto related CI

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
Does presto finally upgraded to higher java version?

@mcvsubbu Do you have plan to move to higher java version?

**Comment by xiangfu0** [comment]
> Does presto finally upgraded to higher java version?
> 
> @mcvsubbu Do you have plan to move to higher java version?

No, presto is still on jdk8.

I will write a separated thing for presto.

We shouldn't carry other project's tech debt on us.

**Review by snleee — COMMENTED** [review]
@xiangfu0 Just to confirm, we may spin up the presto connector in a separate github repo?

LGTM !

**Comment by xiangfu0** [comment]
> @xiangfu0 Just to confirm, we may spin up the presto connector in a separate github repo?
> 
> LGTM !

yes, or just move all the client side logic to PrestoDB repo.

Since Trino side in on higher JDK, so Trino can directly import pinot libs from Maven.

**Pull request merged**
