### PR TITLE
[SchemaConformingTransformer]Add one more json_data field

### PR DESCRIPTION
**Pull request by lnbest0707-uber**
`feature` `ingestion`
To ingest json-like data through SchemaConformingTransformer, previously, we could only dump data to either dedicated column or a single json_data field. We may build json index on json_data field to serve queries.
However, in reality, users may e.g. dump data like request/response body to the json data and query them. For those special json field, they may want special treatment like more levels of json index.
With this patch, among the non-dedicated column data, we will be able to dump them to either default field or a special field filtered by its prefix. And in real use cases, users could choose to build more index or add other special treatments to it.

One example, user might set 3 levels json on the default `json_data` field but needs some part of json (e.g. `request` and `response`) has deeper level index, e.g. 5.
Then they could set `indexableSpecialFieldPrefix: ["request", "response"]` in the SchemaConformingTransformerV2 config, and add `json_data_inf_idx` as json index in the config with 5 levels.
```
"schemaConformingTransformerV2Config": {
        "enableIndexableExtras": true,
        "indexableExtrasField": "json_data",
        "enableUnindexableExtras": true,
        "indexableSpecialFieldPrefix": ["request", "response"],
        "indexableSpecialField": "json_data_inf_idx",
        "unindexableExtrasField": "json_data_no_idx",
        "unindexableFieldSuffix": "_noindex",
        "fieldPathsToDrop": [],
        "fieldPathsToSkipStorage": [
          "message"
        ],
        "columnNameToJsonKeyPathMap": {},
        "mergedTextIndexFields": [
          "__mergedTextIndex"
        ],
        "optimizeCaseInsensitiveSearch": false,
        "reverseTextIndexKeyValueOrder": true,
        "mergedTextIndexDocumentMaxLength": 32766,
        "mergedTextIndexBinaryDocumentDetectionMinLength": 512,
        "mergedTextIndexPathToExclude": [
          "_timestampMillisNegative",
          "__mergedTextIndex",
          "_timestampMillis"
        ],
        "fieldsToDoubleIngest": [],
        "jsonKeyValueSeparator": "\u001e",
        "mergedTextIndexBeginOfDocAnchor": "\u0002",
        "mergedTextIndexEndOfDocAnchor": "\u0003",
        "fieldPathsToPreserveInput": [],
        "fieldPathsToPreserveInputWithIndex": []
      },
"jsonIndexConfigs": {
        "json_data": {
          "disabled": false,
          "maxLevels": 3,
          "excludeArray": true,
          "disableCrossArrayUnnest": true,
          "maxValueLength": 1000,
          "skipInvalidJson": true
        },
      "json_data_inf_idx": {
          "disabled": false,
          "maxLevels": 5,
          "excludeArray": true,
          "disableCrossArrayUnnest": true,
          "maxValueLength": 1000,
          "skipInvalidJson": true
        }
      },
```

### CODE REVIEW

**Review by itschrispeck — APPROVED** [review]

**Comment by chenboat** [comment]
> However, in reality, users may e.g. dump data like request/response body to the json data and query them. For those special json field, they may want special treatment like more levels of json index. 

Can you add one example with data to illustrate the use case?

> With this patch, among the non-dedicated column data, we will be able to dump them to either default field or a special field filtered by its prefix. And in real use cases, users could choose to build more index or add other special treatments to it.

One example can be added to explain the new feature added in the PR summary.  Are you also proposing another new config to the transfer? If so, please list it in the summary too.

**Comment by lnbest0707-uber** [comment]
> > However, in reality, users may e.g. dump data like request/response body to the json data and query them. For those special json field, they may want special treatment like more levels of json index.
> 
> Can you add one example with data to illustrate the use case?
> 
> > With this patch, among the non-dedicated column data, we will be able to dump them to either default field or a special field filtered by its prefix. And in real use cases, users could choose to build more index or add other special treatments to it.
> 
> One example can be added to explain the new feature added in the PR summary. Are you also proposing another new config to the transfer? If so, please list it in the summary too.

Thanks for the review, updated the summary with an example.

**Comment by chenboat** [comment]
Why can't we use the _includePaths_ config in Json index configuration option to explicitly index a certain path with any depth? 

 https://docs.pinot.apache.org/basics/indexing/json-index#enable-and-configure-a-json-index

**Comment by lnbest0707-uber** [comment]
> Why can't we use the _includePaths_ config in Json index configuration option to explicitly index a certain path with any depth?
> 
> https://docs.pinot.apache.org/basics/indexing/json-index#enable-and-configure-a-json-index

IIUC, the `includePaths` config is specified in the json index config of a field like
```
"json_data": {
      "disabled": false,
      "maxLevels": 3,
      "excludeArray": true,
      "disableCrossArrayUnnest": true,
      "maxValueLength": 1000,
     "includePaths": ["request", "response"],
      "skipInvalidJson": true
},
```
But the behavior will be only `["request", "response"]` in json_data field could have json index, but other fields cannot have the json index. This is not what users might want as `["request", "response"]` with 5 levels index but rest with 3 levels index.

**Comment by lnbest0707-uber** [comment]
Abandon the change, will use https://github.com/apache/pinot/pull/14200 instead

**Pull request closed without merging**
