### PR TITLE
fix netty-bom import

### PR DESCRIPTION
**Pull request by walterddr**
import scope should be defined in DependencyManagement section

### CODE REVIEW

**Review by richardstartin — APPROVED** [review]
👍

**Review by Jackie-Jiang — APPROVED** [review]

**Review by Jackie-Jiang — COMMENTED** [review]
Can we put this into the root pom dependency management?

**Review by Jackie-Jiang — APPROVED** [review]
LGTM and much cleaner! @jasperjiaguo Could you please also take a look and see if it can handle your use case?

**Comment by jasperjiaguo** [comment]
Yes LGTM. Thanks for fixing this! @walterddr

**Pull request merged**
