### PR TITLE
Egalpin/skip indexes minor changes

### PR DESCRIPTION
**Pull request by egalpin**
Relates to https://github.com/apache/pinot/pull/12414. Minor naming changes based on PR comments.  

cc/ @Jackie-Jiang @gortiz

### CODE REVIEW

**Review by Jackie-Jiang — APPROVED** [review]
Thank you!

**Comment by Jackie-Jiang** [comment]
Can you please take a look at the test failures?

**Comment by egalpin** [comment]
@Jackie-Jiang all set, I believe the first tests that failed were due to noisy remote test environment.  I tried to make a change to account for the failures in https://github.com/apache/pinot/pull/12514/commits/733d17973ac677098527db527e2b7387b6ff9a9f, which was simply misguided.

**Comment by Jackie-Jiang** [comment]
Thank you for addressing the comments! Can you help contribute this new query option to the pinot doc?

**Pull request merged**
