### PR TITLE
Change DateTimeFormatSpec delimiter 

### PR DESCRIPTION
**Pull request by stym06**
For issue #8632 , this PR is for changing the format in the DateTimeFieldSpec.

### CODE REVIEW

**Review by walterddr — COMMENTED** [review]
thanks for the contribution @stym06 . this looks super great.

please take a look at these tips to get CI green
- for the linter errors: you can use `.github/workflows/scripts/.pinot_linter.sh` to run it locally and fix the issues.
- you will encounter test failure because of this change when you run `mvn test`. please let me know if any of these test issues are not clear or not easy to resolve.

**Review by Jackie-Jiang — COMMENTED** [review]
Thanks for the contribution!
The new format support looks good, but we want to keep it backward compatible so that existing schema still work. Essentially we need to support both format for now, and then slowly deprecate the old format. In the test, we should also test both the old and new format to ensure the change is backward compatible

**Comment by stym06** [comment]
Got it @Jackie-Jiang 

I will make the required changes

**Comment by stym06** [comment]
Created another PR  #8779 with backward compatibility as there were multiple merge conflicts and stuff in this branch.

**Pull request closed without merging**
