### PR TITLE
Upgrade joda-time lib and timezone index

### PR DESCRIPTION
**Pull request by xiangfu0**
- upgrade joda-time from 2.11.2 to 2.12.5
- remove a deprecated time zone `US/Pacific-New`

### CODE REVIEW

**Review by walterddr — COMMENTED** [review]
looks like test all failed?

**Review by snleee — APPROVED** [review]
LGTM

**Comment by walterddr** [comment]
test failure seems legit
```
   ResourceBasedQueriesTest.testQueryTestCasesWithOutput:264->lambda$testQueryTestCasesWithOutput$3:264->QueryRunnerTestBase.compareRowEquals:338 Not match at (0,0)! Expected: [450] Actual: [0] expected [0] but found [-1]
Error:    ResourceBasedQueriesTest.testQueryTestCasesWithOutput:264->lambda$testQueryTestCasesWithOutput$3:264->QueryRunnerTestBase.compareRowEquals:338 Not match at (0,0)! Expected: [0] Actual: [-86400000] expected [0] but found [-1]
```

**Comment by xiangfu0** [comment]
> 

The issue is due to the time zone difference, I got it running on PDT, but CI runs from UTC I guess.

**Pull request merged**
