### PR TITLE
add option to wrap lines in custom code mirror

### PR DESCRIPTION
**Pull request by jadami10**
## Description

Many of the zookeeper nodes contain quite long metadata, and it's challenging to scroll horizontally to read them.

- Adds a toggle to wrap lines for the CustomCodeMirror
- uses it in the zk browser

Note: i had to test with material-ui: 4.12.3 becuase the zookeeper browser is refusing to load locally due to some makeStyles issue

Edit table looks the same
image

but zk browser now can wrap lines
pinot_wrap_lines

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
@shahsank3t Can you please help take a look at this?

**Comment by shahsank3t** [comment]
Thank you @jadami10 for this enhancement.
+1, Changes look good to me.
Just one nitpick: should we move the `Wrap lines` toggle on the right-hand side instead of the left? IMO, it's an action and I think it will be better on left. What do you think?

cc: @Jackie-Jiang

**Comment by jadami10** [comment]
I liked it better on the left since that puts it closer to the start of the lines. so if i wrap, i can immediately move the mouse down and copy/paste.

that said, it's not a strong opinion. maybe @Jackie-Jiang can be the tie breaker.

**Comment by Jackie-Jiang** [comment]
@shahsank3t Thanks for the review. I kind of like the way @jadami10 puts it on the left since it requires less mouse movement.

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
