### PR TITLE
[Work In Progress] Avoid setting result column types to STRING when resultset is empty.

### PR DESCRIPTION
**Pull request by amrishlal**
The current codebase sets datatype of columns to STRING while generating an empty resultset after all segments have been pruned out (see Issue #9660 for more details). In this PR, empty result set column datatypes are not set when all segments are pruned out.

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
This is backward-incompatible change, and user might want to get the column names back. Currently it happens when all the segments are pruned. One work-around would be to always keep at least one segment, so that we can get the actual data types

**Comment by amrishlal** [comment]
> This is backward-incompatible change, and user might want to get the column names back. Currently it happens when all the segments are pruned. One work-around would be to always keep at least one segment, so that we can get the actual data types

We can set column names in `buildEmptySelectionQueryResults` functions also, but if we are ok with keeping at least one segment, then it might be possible to set proper column types as well. I can try it out...

**Comment by amrishlal** [comment]
> One work-around would be to always keep at least one segment, so that we can get the actual data types

@Jackie-Jiang This works very well :-) Great Idea. Allows for properly setting types (even when expressions are used in the select list) when the rest is empty. This is same as what Postgres and Mysql do. The only caveat is that the query will get executed against at least one segment.

**Comment by Jackie-Jiang** [comment]
There are 2 types of pruning, one is to prune the invalid segments (empty or column does not exist), the other is value based. We cannot keep the invalid one because query engine can throw exception against it.

**Pull request closed without merging**
