### PR TITLE
Fix segment replace test

### PR DESCRIPTION
**Pull request by walterddr**
recently there were many instability in `PinotHelixResourceManagerTest.testSegmentReplacementForRefresh` where it stuck at `waitForSegmentsToDelete`. 
e.g. 2 completely different/irrelevant PR failed on this:
https://github.com/apache/pinot/runs/5194729499?check_suite_focus=true
https://github.com/apache/pinot/runs/5161381187?check_suite_focus=true

This PR moves it to the stateless test so it doesn't run together with other statefuls tests. also simplified the logic to run them sequentially

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
I don't think switching it to stateless is the issue. Per the failure run, extending `TIMEOUT_IN_MS` to 60s should fix the test. Github Actions vm has very limited resource, so we might need to wait longer than what is needed on local box

**Comment by walterddr** [comment]
done. but I think we should move it over anyway. 
originally the idea was to save startup tear down time using stateful suite. but since we already have "stateless" version of the PinotHelixResourceManagerTest, there's no reason we need the stateful one because we anyway will start a new cluster

**Comment by Jackie-Jiang** [comment]
The logic in the `stateless` test is slightly different, where it actually tests the tenant behavior with fake brokers and servers which doesn't apply to the segment upload where real server might be required (even thought it might not be tested). I'd suggest keeping the test unmoved to limit the change and see if changing timeout fixes the issue.

**Comment by walterddr** [comment]
> The logic in the `stateless` test is slightly different, where it actually tests the tenant behavior with fake brokers and servers which doesn't apply to the segment upload where real server might be required (even thought it might not be tested). I'd suggest keeping the test unmoved to limit the change and see if changing timeout fixes the issue.

sounds good. 
although i still think the test should be stateless, for one it is not suppose to test against server/broker logic in pinot-controller module which it does in the stateful test class; also it worked perfectly in stateless test.
however given we don't have a test to cover the lineage logic in broker/server separately. i would agree to keep the current behavior (though it is much slower)

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
