### PR TITLE
Use builder method for initalizing immutable map in integration test

### PR DESCRIPTION
**Pull request by eaugene**
Fixes: https://github.com/apache/pinot/issues/11563 

cc : @saurabhd336

### CODE REVIEW

**Comment by saurabhd336** [comment]
While this change can be merged regardless, I'm unable to repro the issue https://github.com/apache/pinot/issues/11563. Could you please add more details on steps to repro? Thanks

**Review by xiangfu0 — APPROVED** [review]

**Comment by siddharthteotia** [comment]
Seems like a harmless change to make it use builder. However, what exactly is the issue  ?

**Comment by eaugene** [comment]
@siddharthteotia Building pinot-integration-tests is failing as a suitable method in guava cannot be found .
More Info on : https://github.com/apache/pinot/issues/11563

**Comment by ege-st** [comment]
@eaugene I know this PR was already merged, but something in this caused our code coverage to drop from 63% to 14% and given that we've been holding a steady 63% for a few months I think this change must've indirectly affected something and we should double check just to make sure it's benign.  Thanks!

**Comment by eaugene** [comment]
> @eaugene I know this PR was already merged, but something in this caused our code coverage to drop from 63% to 14% and given that we've been holding a steady 63% for a few months I think this change must've indirectly affected something and we should double check just to make sure it's benign. Thanks!

@ege-st  Checked the codecov report says it still stays as 63% https://app.codecov.io/gh/apache/pinot/pull/11564/commits . Likely some intermittent issue with codecov github reporter

**Comment by Jackie-Jiang** [comment]
@ege-st Usually that 14% is caused by codecov posting report prematurely before receiving all coverage files. We should probably see if there is some config we can tune to fix this

**Pull request merged**
