### PR TITLE
Log table config and schema updates

### PR DESCRIPTION
**Pull request by yashmayya**
- Currently, changes to table configs and schemas aren't logged. This makes debugging the history of a table difficult.
- This minor patch adds info logs to the `addSchema`, `updateSchema`, `addTable`, `updateTableConfig` APIs.
- Sample logs:

```
Successfully created new schema: {
  "schemaName" : "testSchema",
  "enableColumnBasedNullHandling" : false,
  "dimensionFieldSpecs" : [ {
    "name" : "OldColumn",
    "dataType" : "INT",
    "notNull" : false
  } ]
}
```

```
Successfully updated schema: testSchema with new value: {
  "schemaName" : "testSchema",
  "enableColumnBasedNullHandling" : false,
  "dimensionFieldSpecs" : [ {
    "name" : "NewColumn",
    "dataType" : "STRING",
    "notNull" : false
  }, {
    "name" : "OldColumn",
    "dataType" : "INT",
    "notNull" : false
  } ]
}
```

```
Successfully added table with name: airlineStats_OFFLINE and config: {"tableName":"airlineStats_OFFLINE","tableType":"OFFLINE","segmentsConfig":{"timeColumnName":"DaysSinceEpoch","timeType":"DAYS","replication":"1","segmentPushType":"APPEND","minimizeDataMovement":false,"segmentAssignmentStrategy":"BalanceNumSegmentAssignmentStrategy"},"tenants":{"broker":"DefaultTenant","server":"DefaultTenant"},"tableIndexConfig":{"aggregateMetrics":false,"starTreeIndexConfigs":[{"dimensionsSplitOrder":["AirlineID","Origin","Dest"],"functionColumnPairs":["COUNT__*","MAX__ArrDelay"],"maxLeafRecords":10}],"enableDefaultStarTree":false,"rangeIndexVersion":2,"loadMode":"MMAP","tierOverwrites":{"hotTier":{"starTreeIndexConfigs":[{"dimensionsSplitOrder":["Carrier","CancellationCode","Origin","Dest"],"skipStarNodeCreationForDimensions":[],"functionColumnPairs":["MAX__CarrierDelay","AVG__CarrierDelay"],"maxLeafRecords":10}]},"coldTier":{"starTreeIndexConfigs":[]}},"nullHandlingEnabled":false,"optimizeDictionary":false,"autoGeneratedInvertedIndex":false,"enableDynamicStarTreeCreation":true,"columnMajorSegmentBuilderEnabled":true,"optimizeDictionaryForMetrics":false,"noDictionarySizeRatioThreshold":0.85,"createInvertedIndexDuringSegmentGeneration":false},"metadata":{"customConfigs":{}},"fieldConfigList":[{"name":"ts","encodingType":"DICTIONARY","indexType":"TIMESTAMP","indexTypes":["TIMESTAMP"],"timestampConfig":{"granularities":["DAY","WEEK","MONTH"]},"indexes":null,"tierOverwrites":null},{"name":"ArrTimeBlk","encodingType":"DICTIONARY","indexTypes":[],"indexes":{"inverted":{"enabled":"true"}},"tierOverwrites":{"hotTier":{"encodingType":"DICTIONARY","indexes":{"bloom":{"enabled":"true"}}},"coldTier":{"encodingType":"RAW","indexes":{"text":{"enabled":"true"}}}}}],"ingestionConfig":{"transformConfigs":[{"columnName":"ts","transformFunction":"fromEpochDays(DaysSinceEpoch)"},{"columnName":"tsRaw","transformFunction":"fromEpochDays(DaysSinceEpoch)"}],"segmentTimeValueCheck":true,"rowTimeValueCheck":false,"continueOnError":false},"tierConfigs":[{"name":"hotTier","segmentSelectorType":"time","segmentAge":"3130d","storageType":"pinot_server","serverTag":"DefaultTenant_OFFLINE"},{"name":"coldTier","segmentSelectorType":"time","segmentAge":"3140d","storageType":"pinot_server","serverTag":"DefaultTenant_OFFLINE"}],"isDimTable":false}
```

```
Successfully updated table config for table: airlineStats_OFFLINE with new config: {"tableName":"airlineStats_OFFLINE","tableType":"OFFLINE","segmentsConfig":{"timeColumnName":"DaysSinceEpoch","timeType":"DAYS","replication":"1","segmentPushType":"APPEND","minimizeDataMovement":false,"segmentAssignmentStrategy":"BalanceNumSegmentAssignmentStrategy"},"tenants":{"broker":"DefaultTenant","server":"DefaultTenant"},"tableIndexConfig":{"aggregateMetrics":false,"starTreeIndexConfigs":[{"dimensionsSplitOrder":["AirlineID","Origin","Dest"],"functionColumnPairs":["COUNT__*","MAX__ArrDelay"],"maxLeafRecords":10}],"enableDefaultStarTree":false,"rangeIndexVersion":2,"loadMode":"MMAP","tierOverwrites":{"hotTier":{"starTreeIndexConfigs":[{"dimensionsSplitOrder":["Carrier","CancellationCode","Origin","Dest"],"skipStarNodeCreationForDimensions":[],"functionColumnPairs":["MAX__CarrierDelay","AVG__CarrierDelay"],"maxLeafRecords":10}]},"coldTier":{"starTreeIndexConfigs":[]}},"nullHandlingEnabled":false,"optimizeDictionary":false,"autoGeneratedInvertedIndex":false,"enableDynamicStarTreeCreation":false,"columnMajorSegmentBuilderEnabled":true,"optimizeDictionaryForMetrics":false,"noDictionarySizeRatioThreshold":0.85,"createInvertedIndexDuringSegmentGeneration":false},"metadata":{"customConfigs":{}},"fieldConfigList":[{"name":"ts","encodingType":"DICTIONARY","indexType":"TIMESTAMP","indexTypes":["TIMESTAMP"],"timestampConfig":{"granularities":["DAY","WEEK","MONTH"]},"indexes":null,"tierOverwrites":null},{"name":"ArrTimeBlk","encodingType":"DICTIONARY","indexTypes":[],"indexes":{"inverted":{"enabled":"true"}},"tierOverwrites":{"hotTier":{"encodingType":"DICTIONARY","indexes":{"bloom":{"enabled":"true"}}},"coldTier":{"encodingType":"RAW","indexes":{"text":{"enabled":"true"}}}}}],"ingestionConfig":{"transformConfigs":[{"columnName":"ts","transformFunction":"fromEpochDays(DaysSinceEpoch)"},{"columnName":"tsRaw","transformFunction":"fromEpochDays(DaysSinceEpoch)"}],"segmentTimeValueCheck":true,"rowTimeValueCheck":false,"continueOnError":false},"tierConfigs":[{"name":"hotTier","segmentSelectorType":"time","segmentAge":"3130d","storageType":"pinot_server","serverTag":"DefaultTenant_OFFLINE"},{"name":"coldTier","segmentSelectorType":"time","segmentAge":"3140d","storageType":"pinot_server","serverTag":"DefaultTenant_OFFLINE"}],"isDimTable":false}
```

### CODE REVIEW

**Comment by gortiz** [comment]
Two suggestions:

1. Can we unify logs (apply the same change I suggested for schema in table config)?
2. Can we create a similar log when tables are deleted. If possible, using the same log pattern so the same regex can be used.

**Comment by yashmayya** [comment]
I've updated the log lines to be uniform but I'm a little skeptical about the table deletion log. I'm worried that users will be misled into believing that the deletion process is over whereas segments will continue to be deleted async from the servers.

Edit: Never mind, I just noticed that the API response anyway states that the tables were deleted.

**Review by gortiz — APPROVED** [review]
If you are concerned about the async nature of these processes, we can change the messages to: _Successfully schedule to (delete/update/create)_

**Comment by yashmayya** [comment]
I think let's keep it to what it is currently since the logs are emitted after the Helix / ZK state is updated and that is user visible. Also, I guess users should already be familiar with the async nature from the current success API responses.

**Pull request merged**
