### PR TITLE
[#13862] add --host option to pinot-admin.sh StartKafka

### LINKED ISSUE #13862: allow kafka to listen on other interfaces instead of localhost
Add an option "--host" to `bin/pinot-admin.sh StartKafka`.

### PR DESCRIPTION
**Pull request by yjqg6666**
Fixes #13862. 

Instructions:
1. The PR has to be tagged with at least one of the following labels (*):
   1. `feature`
   2. `bugfix`

 
(*) Other labels to consider:
- `tools`
- `release-notes`

(**) Use `release-notes` label for scenarios like:
- Add "--host" option to `bin/pinot-admin.sh StartKafka`

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
Trying to understand the usage. Can you share more on when do you want to specify a host other than local?

**Comment by yjqg6666** [comment]
When the producer(s) and/or consumer(s) are deployed at the other machines, they need to connect to the bootstrap server.

**Comment by Jackie-Jiang** [comment]
We may configure the table to point to a remote kafka broker, but `StartKafkaCommand` should always start the Kafka cluster locally unless I missed something. cc @xiangfu0 @swaminathanmanish

**Comment by Jackie-Jiang** [comment]
@yjqg6666 is #12209 similar to the problem you are trying to solve?

**Comment by yjqg6666** [comment]
For production deployment, not all the components (controller, broker, server) are deployed at the same server. I guess here the kafka server is for ingress message digesting (kafka streaming), the other biz application need to push data to the kafka broker. I am deploying [apm-pinpoint](https://github.com/pinpoint-apm/pinpoint) which use pinot for realtime data analysis.

**Comment by Jackie-Jiang** [comment]
I see. The StartKafka command is mostly for local testing purpose, which starts a Kafka broker. In production, you should already have Kafka deployed, so you can simply point to your Kafka broker in the table config.

**Pull request closed without merging**
