### PR TITLE
add theta sketch scalar

### PR DESCRIPTION
**Pull request by walterddr**
added several functions
- `GET_THETA_SKETCH_ESTIMATE` to extract estimate from ThetaSketch
- `THETA_SKETCH_DIFF` to differentiate 2 ThetaSketch
- `THETA_SKETCH_UNION`/`THETA_SKETCH_INTERSECT` for ThetaSketch set operations

syntax examples:
```
select 
  GET_THETA_SKETCH_ESTIMATE(DISTINCTCOUNTRAWTHETASKETCH(runs, '')),
  GET_THETA_SKETCH_ESTIMATE(THETA_SKETCH_DIFF(DISTINCTCOUNTRAWTHETASKETCH(runs, ''), DISTINCTCOUNTRAWTHETASKETCH(runs, ''))),
  GET_THETA_SKETCH_ESTIMATE(THETA_SKETCH_UNION(DISTINCTCOUNTRAWTHETASKETCH(runs, ''), DISTINCTCOUNTRAWTHETASKETCH(runs, ''))),
  GET_THETA_SKETCH_ESTIMATE(THETA_SKETCH_INTERSECT(DISTINCTCOUNTRAWTHETASKETCH(runs, ''), DISTINCTCOUNTRAWTHETASKETCH(runs, '')))
from baseballStats limit 10
```

### CODE REVIEW

**Comment by mayankshriv** [comment]
Why not put this in OSS?

**Comment by cbalci** [comment]
This is pretty cool, but I'd suggest we prefix the function names with sketch types, ie `THETA_SKETCH_GET_ESTIMATE`, since we use different sketches (KLL, Tuples etc.) and more coming.

**Comment by walterddr** [comment]
> This is pretty cool, but I'd suggest we prefix the function names with sketch types, ie `THETA_SKETCH_GET_ESTIMATE`, since we use different sketches (KLL, Tuples etc.) and more coming.

Ahh. LOL i didn't know KLL and Tuples are actually a different sketches :-) thank you for the notes.

**Comment by cbalci** [comment]
Right, 'sketch' is a generic term for various probabilistic data structures and different sketches have different binary layouts and serializers/deserializers. It would be hard to write a generic function which handles all. The one you are using in this PR is for `ThetaSketch` only.

Even if we manage to identify they sketch type from serialized form, interfaces may differ. For example `ThetaSketch` and `TuplesSketch` are 'distinctcount' type sketches and offer a `.getEstimate` interface, while `KLLSketch` is a 'percentile' type sketch which has a `.getQuantile` interface. 

Hope this makes sense.

**Comment by walterddr** [comment]
ok so to summarize:

- we should have a `getSketchEstimate` and `getSketchQuantile` method which should figure out if the sketch object allows such function (this can be done as a follow up with customized defined type
- for setUnion/Intersect/Diff only the same type of sketches are allowed to perform set operation. 

feels like this should be handled by type matching instead of function name.

**Review by xiangfu0 — APPROVED** [review]

**Pull request merged**
