### PR TITLE
add table sort function for table size

### PR DESCRIPTION
**Pull request by jadami10**
addresses #9843

this is a `ui` `bugfix`

This is probably not the greatest way to do this. Transforming the data from bytes -> humanized -> bytes just to sort it feels hacky. But short of reworking `CustomTable` to track real vs display value, this is probably the fastest way to get this.

I tested by creating some fake tables locally and force committing them to get different sizes. I can't test on a bigger cluster until next week, so someone else might want to ensure this looks good as well.

https://user-images.githubusercontent.com/4760722/203428724-e8d781e1-d68e-43e5-a514-ca4eec5b1df3.mov

### CODE REVIEW

**Comment by jadami10** [comment]
@jayeshchoudhary mind having a look here?

**Review by jayeshchoudhary — APPROVED** [review]
Agree this is not the best way to handle sorting but given that the custom table implementation is very restrictive and not generic at all, this solution looks good. 

Thanks @jadami10 for this 🙂

**Comment by jadami10** [comment]
I changed the code locally to return random bytes. Sorting seems to work well.

```
function getRandomInt(min, max) {
        min = Math.ceil(min);
        max = Math.floor(max);
        return Math.floor(Math.random() * (max - min) + min); // The maximum is exclusive and the minimum is inclusive
      }

      results.map((result, index) => {
        // since we have 3 promises, we are using mod 3 below
        if (index % 3 === 0) {
          const kb = 1000;
          const mb = kb * 1000;
          const gb = mb * 1000;
          const tb = gb * 1000;
          const pb = tb * 1000;
          const sizes = [kb, mb, gb, tb, pb];
          const index = Math.floor(Math.random() * sizes.length);
          const min = Math.max(0, index - 1);
          const max = sizes[index];
          // const max = 1125899906842624;
          // response of getTableSize API
          const {
            tableName,
            reportedSizeInBytes,
            estimatedSizeInBytes,
          } = result.data;
          singleTableData.push(
            tableName,
            Utils.formatBytes(getRandomInt(0, max)),
            Utils.formatBytes(getRandomInt(0, max)),
            // Utils.formatBytes(reportedSizeInBytes),
            // Utils.formatBytes(estimatedSizeInBytes)
          );
        }
```

https://user-images.githubusercontent.com/4760722/205324295-06039912-9b35-4cec-a861-e9211d30ccef.mov

**Review by Jackie-Jiang — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
