### PR TITLE
[DRAFT: DO NOT MERGE] Segment builder use column orientation build test

### PR DESCRIPTION
**Pull request by ege-st**
Testing column major mode.

### CODE REVIEW

**Comment by mcvsubbu** [comment]
Issue #4036 has another draft link (albeit very old)

**Comment by ege-st** [comment]
> Issue #4036 has another draft link (albeit very old)

Oh, cool, I'll take a look at this today.

**Comment by ege-st** [comment]
Not needed now.

**Comment by mcvsubbu** [comment]
Do you mean that we can postpone this effort? Or, are you saying that this is not needed anymore for your use case?

**Pull request closed without merging**
