### PR TITLE
Bug fix. Allow passing null http headers object to translateTableName

### PR DESCRIPTION
**Pull request by shounakmk219**
Addresses issue #12745

### CODE REVIEW

**Review by jackjlli — COMMENTED** [review]
Thanks for addressing it! Does it make sense to put the `@Nullable` annotation to the other caller these two methods, like `handleRequest()` in `BrokerRequestHandler` class?

**Comment by shounakmk219** [comment]
Not sure if implementations of `BrokerRequestHandler. handleRequest` are fine with a null header.
`FineGrainedAccessControl.hasAccess` interface which is invoked in `BaseBrokerRequestHandler.handleRequest` may be sensitive to headers based on provided implementation. 
Technically the util only breaks if invoked through tests with null header as existing code path does not pass a null header anywhere.
I have handled this at [test side code](https://github.com/apache/pinot/pull/12417/files#diff-ef432222ed63283ab900bf309612a3c4b6d2a0d1e15abc76fad46a19b2b1750cR168) itself earlier during introduction of the util.

**Comment by jackjlli** [comment]
Not just the test code which will invoke the real logic, in fact a lot of companies will invoke the handleRequest() method with their own ways. 

> I have handled this at [test side code](https://github.com/apache/pinot/pull/12417/files#diff-ef432222ed63283ab900bf309612a3c4b6d2a0d1e15abc76fad46a19b2b1750cR168) itself earlier during introduction of the util.

And I just tested the code before the [PR](https://github.com/apache/pinot/pull/12417) mentioned above, previously the test did work with a null httpHeaders. But after the code change in that PR it starts to fail with a null httpHeaders. Could you add a unit test for this to make sure the original behavior won't break?

**Review by Jackie-Jiang — APPROVED** [review]
I'm merging it since the fix is very straight forward. We can discuss why `null` values are passed in separately

**Pull request merged**
