### PR TITLE
Update to latest version of clp-ffi that has support for Linux and macOS ARM platforms.

### PR DESCRIPTION
**Pull request by kirkrodrigues**
This updates to the latest release of clp-ffi that has support for Linux and macOS ARM platforms.

This partly addresses #10945.

# Validation performed

On an Apple Silicon Mac, validated unit tests that failed due to a lack of ARM support in clp-ffi@0.4.4 now succeeded with clp-ffi@0.4.5.

### CODE REVIEW

**Comment by kirkrodrigues** [comment]
I think the test failures are unrelated to the change but can't be sure.

**Comment by gortiz** [comment]
After https://github.com/apache/pinot/pull/13648, these tests should be now skipped by default when being executed on aarch64. Have you verify they are being executed? 

cc @suddendust

**Comment by kirkrodrigues** [comment]
> After https://github.com/apache/pinot/pull/13648, these tests should be now skipped by default when being executed on aarch64. Have you verify they have being executed?

Yep, my branch was implemented before #13648 was merged and I had tested that the tests ran on an Apple Silicon Mac. I tested again just now on a Linux aarch64 machine (by removing the `TestUtils.ensureArchitectureIsNotARM()` check and running the CLP tests using clp-ffi@0.4.5). Should we remove the `TestUtils.ensureArchitectureIsNotARM()` check in this PR as well?

**Comment by gortiz** [comment]
>  Should we remove the TestUtils.ensureArchitectureIsNotARM() check in this PR as well?

Yes. The only reason to add them is that these tests didn't work in ARM. Now that they do, we should not call that method.

**Comment by kirkrodrigues** [comment]
> Yes. The only reason to add them is that these tests didn't work in ARM. Now that they do, we should not call that method.

Apologies for the delay. Removed the checks and validated all CLP-related tests pass on a Linux aarch64 machine.

**Comment by kirkrodrigues** [comment]
GH check failure seems unrelated to this change.

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
