### PR TITLE
Refactor: Remove unused schema validator code

### PR DESCRIPTION
**Pull request by ege-st**
The `IngestionSchemaValidator` logic was not used in any code path except for 3 unit tests. It appears as if it was used to validate the schema of a segment versus an Avro schema (as Avro was the only implementation of the Schema Validator). But the validator itself is never executed in any code path of Pinot.

This also removes the `getColumnStatisticsCollector` from `SegmentIndexCreationDriver` as that method was never being called anywhere.

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
@jackjlli I saw you contributed this. Is this still in use?

**Review by jackjlli — CHANGES_REQUESTED** [review]
Hi @ege-st, this schema validator is actively being used inside LinkedIn. Basically it attempts to detect any schema mismatch during segment generation. The stats would be useful to know the quality of the input data. So please do not remove this part of code.

**Comment by Jackie-Jiang** [comment]
@ege-st They are part of `pinot-spi` which is intended to be used by some external tool (not maintained in this repo). Do you run into issues with them?

**Comment by ege-st** [comment]
No worries.  We can kill this pr.

**Comment by ege-st** [comment]
No issues,  but since I couldn't find any path within core Pinot that was
using this logic, I thought the code which uses it might have been removed
at some point.

**Pull request closed without merging**
