### PR TITLE
Allow override of StreamConfig property server upload to deepstore

### PR DESCRIPTION
**Pull request by raghavyadav01**
Currently default value of StreamConfig property "defaultServerUploadToDeepStore" is not configurable and can only be changed through table stream config. 
The change allow the default value to be overridden from derived classes of PinotAdministrator. 

Tests:
1. Added Unit Tests to verify the changes.
2. Validated the changes manually local pinot cluster.

### CODE REVIEW

**Comment by 9aman** [comment]
Can you help me understand how this parameter of the StreamConfig could be changed for server to upload directly to the deepstore without changing the streamConfig in the table config?
Do we need any more changes for this to be effective? I see that streamConfig is at times a local variable or a private field e.g. in SegmentCompletionManager

**Comment by raghavyadav01** [comment]
With the change we are providing a way to override the default value of server to upload setting for  tables globally during controller start. STP side changes will be done once this pr merges. 
Note: User provided value in stream config always takes precedence.

**Review by Jackie-Jiang — COMMENTED** [review]
I'd suggest making it a cluster level config so that people can set it without modifying the code. With current PR, user needs to add custom code in order to set it

**Comment by raghavyadav01** [comment]
@Jackie-Jiang The idea is that default value of config will be false but provide the users to override the default value for tables which does not have the stream level config for server upload to deepstore. 
We do not want to change the default but a way to change default for STP.

**Comment by Jackie-Jiang** [comment]
> @Jackie-Jiang The idea is that default value of config will be false but provide the users to override the default value for tables which does not have the stream level config for server upload to deepstore. We do not want to change the default but a way to change default for STP.

I understand the intention. With the approach in this PR, open source user won't be able to change the default value without modifying the code. Instead, ideally we want user to be able to change this default behavior by putting a cluster config. You may take a look at `CommonConstants.Helix.DEFAULT_HYPERLOGLOG_LOG2M_KEY` which is similar concept

**Comment by raghavyadav01** [comment]
Thanks @Jackie-Jiang for the pointers. I will take a look and make the change.

**Pull request closed without merging**
