### PR TITLE
Use codecov action

### PR DESCRIPTION
**Pull request by xiangfu0**
Use codecov action to replace the deprecated bash

### CODE REVIEW

**Review by apucher — APPROVED** [review]

**Review by walterddr — COMMENTED** [review]
this seems to be the cause for https://github.com/apache/pinot/issues/9467 should we revert?

**Comment by Jackie-Jiang** [comment]
@walterddr v1 has been deprecated and we have observed constant failure before upgrading it to v3. I feel we have to wait for codecov to fix their issue

**Comment by xiangfu0** [comment]
we can change `fail_ci_if_error` from `true` to `false` then?

**Comment by walterddr** [comment]
may be related to: https://github.com/codecov/codecov-action/issues/837

**Pull request merged**
