### PR TITLE
[multistage] Fix AVG Return Type

### PR DESCRIPTION
**Pull request by vvivekiyer**
This PR fixess the return type of AVG aggregation function. The discussion/context behind this change is documented in OSS issue https://github.com/apache/pinot/issues/10318

Added planner tests.

### CODE REVIEW

**Review by walterddr — APPROVED** [review]

**Review by walterddr — COMMENTED** [review]
can you also add a test in runtime to make sure avg on a big decimal column returns a big decimal value? (a simple 2 big-decimal that taking an avg resulting in a double-overflowed result should be suffice)

**Review by somandal — APPROVED** [review]
LGTM!

**Comment by vvivekiyer** [comment]
> can you also add a test in runtime to make sure avg on a big decimal column returns a big decimal value? (a simple 2 big-decimal that taking an avg resulting in a double-overflowed result should be suffice)

@walterddr Oh yeah, I tried adding it earlier. There's a existing issue where none of the aggregation functions work on BIG_DECIMAL columns 😅 . I'll spend some time tomorrow debugging and fixing it.  We can incorporate the fix in this PR or merge this PR and create a separate one for BIG_DECIMAL aggregate functions. I'm ok either way.

**Comment by walterddr** [comment]
> @walterddr Oh yeah, I tried adding it earlier. There's a existing issue where none of the aggregation functions work on BIG_DECIMAL columns 😅 . I'll spend some time tomorrow debugging and fixing it. We can incorporate the fix in this PR or merge this PR and create a separate one for BIG_DECIMAL aggregate functions. I'm ok either way.

ahh. in this case nvm we can fix in follow up PR

**Pull request merged**
