### PR TITLE
support S3 storage class

### PR DESCRIPTION
**Pull request by sullis**
https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
cc @swaminathanmanish

**Comment by sullis** [comment]
rebased

**Comment by sullis** [comment]
Ready for review

**Review by xiangfu0 — APPROVED** [review]

**Comment by xiangfu0** [comment]
Thanks for adding this @sullis !

**Pull request merged**
