### PR TITLE
#5695 Increasing test coverage pinot-common

### PR DESCRIPTION
**Pull request by aditya0811**
[5695](https://github.com/apache/pinot/issues/5695)
 
(*) Other labels to consider:
- `testing`

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
Can you please take a look at the linter failure?
It would be very helpful if you can also include how many missing lines are covered within this new test

**Comment by gortiz** [comment]
It seems there are some compilation issues. Can you fix them?

**Comment by aditya0811** [comment]
> It seems there are some compilation issues. Can you fix them?

updated with latest code, constructor changed

**Comment by aditya0811** [comment]
> Can you please take a look at the linter failure? It would be very helpful if you can also include how many missing lines are covered within this new test

Fixed. covers 79 missing lines, was not able to set up UT for L77.

**Review by gortiz — APPROVED** [review]

**Comment by gortiz** [comment]
Merged, thanks for this contribution and my personal apologies for taking so much time to merge it.

**Comment by aditya0811** [comment]
> Merged, thanks for this contribution and my personal apologies for taking so much time to merge it.

no worries, happy to contribute.

**Pull request merged**
