### PR TITLE
Fix the issue of consuming segment entering ERROR state due to stream connection errors

### PR DESCRIPTION
**Pull request by sajjad-moradi**
## Description

This PR fixes the issue described in #11165 by calling controller to mark the Ideal State for the segment as OFFLINE when there's error in consumer setup (or in general LLRealtimeSegmentDataManager initialization).

## Testing Done
Ran an integration test locally and simulated an exception during initial stream consumer setup: 
Before the problematic segment goes to ERROR state, the IS is marked as OFFLINE for the segment. For a very short period of time, the EV was in ERROR state till Helix kicks off ERROR -> OFFLINE transition for that segment. Then it became OFFLINE. After that kicking off RealtimeSegmentValidationManager created a new consuming segment for the partition.

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
Does it work if we directly send stop consume message when it throws exception in the constructor?

**Comment by sajjad-moradi** [comment]
> Does it work if we directly send stop consume message when it throws exception in the constructor?

That's a great idea. I actually verified that it works as expected:
Before the problematic segment goes to ERROR state, the IS is marked as OFFLINE for the segment. For a very short period of time, the EV is in ERROR state till Helix kicks off `ERROR -> OFFLINE` transition for that segment. Then it becomes OFFLINE. After that kicking off `RealtimeSegmentValidationManager` creates a new consuming segment for the partition.

**Review by Jackie-Jiang — APPROVED** [review]

**Comment by mcvsubbu** [comment]
I am worried that we may not be able to test all combinations of the case if we post a stopConsume message. Does it still work if Helix has not yet gotten around to set externalview to ERROR state?

**Comment by sajjad-moradi** [comment]
> I am worried that we may not be able to test all combinations of the case if we post a stopConsume message. Does it still work if Helix has not yet gotten around to set externalview to ERROR state?

I believe because we've marked IS as OFFLINE, EV will eventually be OFFLINE.
There are two possibilities here [since before throwing exception in handling `OFFLINE->CONSUMING` transition, controller has marked IS as OFFLINE]:
- EV goes to ERROR and then Helix tries to match the current state (ERROR) to ideal state (OFFLINE)
- Helix tries to match IS and EV before EV goes to ERROR. In this case both IS and EV are OFFLINE, so helix doesn't do anything.

In both scenarios, the EV ends up being OFFLINE for the segment.

**Pull request merged**
