### PR TITLE
[issue-8297] upgrade netty due to security concerns

### PR DESCRIPTION
**Pull request by pjfanning**
## Description

update netty jars due to security concerns

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

**Comment by GSharayu** [comment]
Hi @pjfanning , Can you please rebase this PR with latest master

**Comment by GSharayu** [comment]
cc @jackjlli @siddharthteotia @jasperjiaguo

**Comment by siddharthteotia** [comment]
Please rebase

**Comment by pjfanning** [comment]
I rebased this but there are problems with pinot-pulsar and its unit tests. It appears that something in the version of pulsar that pinot-pulsar uses that relies on the old netty.

I'm not an expert on pinot or pulsar and might need to leave this to someone else to solve.

It might be better to upgrade pulsar first before trying to update netty.

**Pull request closed without merging**
