### PR TITLE
Update grpc to 1.53.0 and protobuf to 3.22.0

### PR DESCRIPTION
**Pull request by aahmed-se**
* This fixes the hard coded version of protobuf in pinot-protobuf
* This also allows building the project on arch_64 platforms

### CODE REVIEW

**Review by gortiz — APPROVED** [review]
LGTM although I don't know grpc well enough to understand the impact of increasing the default version

**Review by walterddr — APPROVED** [review]
lgtm.

**Comment by walterddr** [comment]
upon checking the CI job there are some significant regression on test speed. i will return the CI jobs to make sure the regression is not due to resource issue on GHA

**Comment by aahmed-se** [comment]
@walterddr can this be merged now.

**Review by xiangfu0 — APPROVED** [review]

**Comment by walterddr** [comment]
Upon looking at the CI results the 2nd run is still 5-10% slower.

**Comment by gortiz** [comment]
With this new pom.xml we can use different grpc and protobuf versions to see which version is the one that introduce the performance degradation, right?

**Pull request merged**
