### PR TITLE
Upgrade async-http-client to 3.0

### PR DESCRIPTION
**Pull request by sullis**
Version 3.0.0

https://github.com/AsyncHttpClient/async-http-client/releases/tag/async-http-client-project-3.0.0

### CODE REVIEW

**Comment by sullis** [comment]
fyi @hyperxpro

**Comment by sullis** [comment]
CI build is passing 👍

**Comment by sullis** [comment]
Ready for review

**Comment by sullis** [comment]
Ready for review.

**Review by Jackie-Jiang — APPROVED** [review]

**Pull request merged**
